### ISSUE TITLE
Reload calls during reloading should restart reload

### ISSUE THREAD

**Issue by alexstgeorge** [mousebird-consulting-inc/WhirlyGlobe#1039]
Hi,
I've noticed that if a MaplyQuadImageTilesLayer calls it's reload function while it is currently reloading, it seems to ignore the new reload request and continue with the current reloading process. This causes the layer to load in a mixture of the old and new tiles which looks strange on the map. Although this does not happen frequently, I think the proper way to handle subsequent reloads would be to cancel the current reload and restart the reloading process. This would ensure that only the correct tiles are loaded in.

I'm using the 2.5 binary distribution

Thank you.

**Comment by alexstgeorge** [comment]
Ok I look forward to seeing a newer version then. Thanks again!

**Comment by TimSylvester-mousebird** [comment]
Fixed in 3.x with frame generations.
