### ISSUE TITLE
[Android] setHeading animation?

### ISSUE THREAD

**Issue by shaqu1988** [mousebird-consulting-inc/WhirlyGlobe#1071]
Hello,

Is there any possibility to animate setHeading on Android like on iOS - animateToPositionD:height:heading:time?

Thanks!

**Comment by mousebird** [comment]
There's an animatePositionGeo, but we lack the full animation interface on Android.

**Comment by TimSylvester-mousebird** [comment]
Present and seems to work in 3.x.
