### ISSUE TITLE
[Android] Background color for labels

### ISSUE THREAD

**Issue by Tourmen** [mousebird-consulting-inc/WhirlyGlobe#1122]
Hi team.
Ive tried to set up a background color for a ScreenLabel object and it does not work. Neither with an several month old library nor with the latest one built from sources.
Can it be fixed soon?

**Comment by mousebird** [comment]
This is a low level rendering problem.  I'm looking into it.

**Comment by TimSylvester-mousebird** [comment]
Seems to have been fixed a long time ago.
