### ISSUE TITLE
[Android] Issue with refresh method

### ISSUE THREAD

**Issue by Tourmen** [mousebird-consulting-inc/WhirlyGlobe#1133]
Ive tried to call QuadPagingLayer refresh() method. And seems it does nothing. 
There are ScreenMarkers on the globe, but I dont see anything that tells me it is being refreshing.
Can you confirm this issue or clarify how should I use the refresh() method?

**Comment by mousebird** [comment]
I looked through the code and it is calling the JNI refresh which does call all the way down into the QuadDisplayController::refresh.

What you should see is every object associated with that QuadPagingLayer being removed and then each tile added again.  Try putting a log statement in your tile loader to see if it's being called.

**Comment by Tourmen** [comment]
It does go to JNI layer. But I dont see anything that can tell me it works.
Something may be happened, but no one marker even blinked.

**Comment by mousebird** [comment]
What about print statements in your load method?

**Comment by Tourmen** [comment]
Ive found two nuances here:

1. there is a method refresh() in QuadPagingLayer.java class:


```
public void refresh()
	{
		if (!valid)
			return;

		// Make sure this runs on the layer thread
		if (Looper.myLooper() != layerThread.getLooper())
		{
			Handler handle = new Handler();
			handle.post(
					new Runnable() 
					{
						@Override
						public void run()
						{
							refresh();
						}
					});
			return;
		}
		
		ChangeSet changes = new ChangeSet();
		boolean doEvalStep = nativeRefresh(changes);
		layerThread.addChanges(changes);
		if (doEvalStep)
			scheduleEvalStep();
	}
```

Using the examples in AutoTester project, this method calls itself infinitely. So, was not able to dive deeper correctly.

2. Calling refresh() method does not mean WG engine refresh related stuff automatically. I realized I need to catch tileUnload() and startFetchForTile() and do corresponding actions by myself.

After I have managed these steps eventually, I was able to get needed result.

Thank you for support.

**Comment by mousebird** [comment]
#2 - Yes that's correct.

#1 - That code looks a little dodgy.  It should be posting the runnable on the layer thread, but I'm not sure it does.  Were you ever able to get your startFetchForTile called?

**Comment by Tourmen** [comment]
I was not able to get native calls with handle.post(...) initially. 
Then I changed this code with layerThread.addTask(...) and got startFetchForTile calls.

**Comment by Tourmen** [comment]
Also, an interesting issue has been found in addition.
refresh() works 1 or 2 times. Then it stops to work.
No startFetch, no tileUnload callbacks.

**Comment by mousebird** [comment]
I'll set up a test on my side and take a look.

**Comment by TimSylvester-mousebird** [comment]
`QuadPagingLayer` has been replaced with `QuadPagingLoader` in 3.x.  `reload` and `reloadArea` seem to be working.
