### ISSUE TITLE
[Android] LocationTracking implementation

### ISSUE THREAD

**Issue by felipenegrelli** [mousebird-consulting-inc/WhirlyGlobe#1151]
Is Location Tracking implemented for Android?
I found examples for IOS but not for Android. 

If not, are you guys planning on doing it?

By the way, thanks for this great tool!

**Comment by mousebird** [comment]
Not on Android I'm afraid.

Not currently planned either.  None of the participants in the 3.0 effort use location tracking.

I'd be happy to add it for development money, of course.

**Comment by TimSylvester-mousebird** [comment]
Android location tracking was added to main in 3.2.
