### ISSUE TITLE
[Android] setZoomLimits method has no effect

### ISSUE THREAD

**Issue by MSBilgin** [mousebird-consulting-inc/WhirlyGlobe#1159]
I use [2.6.2 aar](https://s3-us-west-1.amazonaws.com/whirlyglobemaplydistribution/WhirlyGlobe-Maply_Distribution_2_6_2.aar) library. Only added mbtiles layer same as your tutorials. I am setting MapControl object max zoom to 28 limits by using **setZoomLimits** method but there is no change. I noticed that mbtiles layers **getTargetZoomLevel**  method returns "Zoom 0 -> 23". And mapcontrol max zoom is 23.330249328502564

**Comment by MSBilgin** [comment]
Also I extended a class from **MBTilesImageSource** to delegate **maxZoom** method. But no luck. There are detailed vector objects. I need to zoom too close.

**Comment by mousebird** [comment]
The terminology is confusing.  ZoomLimits on the MapControl (or GlobeController) refers to the height above the ground of the viewer.  The units are radius of the earth (roughly).  So 1.0 would be looking down at a distance of roughly the radius of the earth.

Zoom limits on the MBTiles files are the normal zoom levels you're accustomed to.

**Comment by MSBilgin** [comment]
My mbtiles dataset max level is 19 but i can zoom to level 23. Maybe pixels getting coarse but works. Is it possible to zoom more. Because my vector objects are detailed, with this low zoom level users cant spot them. Google maps, CartoDb cant do this so i eliminated them.

**Comment by mousebird** [comment]
You can set the zoomLimits on the control to get a bit closer, perhaps.  See what the limits are currently and try setting the min limit to 1/10 of its current value.

**Comment by MSBilgin** [comment]
Can i go down to level 28

**Comment by mousebird** [comment]
The toolkit doesn't evaluate viewing in terms of levels.  It thinks in terms of distance.  Why?  Because we're reprojecting data constantly and we can display multiple data sources at once so what level you're looking at is a confusing concept.

You have to get closer to the data and to do that you have to set the zoomLimits closer.  You can try setting the min zoom limit smaller than it currently is, as I said above.

**Comment by MSBilgin** [comment]
I set zoom limits by 
`mapControl.setZoomLimits(0.00000001, 1);`

and then zoom map as possible as i can. The image is here. And then i get current zoom level by calling 
`mapControl.currentMapZoom(mapControl.getCurrentViewGeo().middle()));`

it returned **23.32851619201422**. I increase zeros like **0.00000000000001**  but not affected.



![device-2019-04-11-161932](https://user-images.githubusercontent.com/6252718/55960530-aa52e880-5c75-11e9-9367-1f71ea2f491a.png)
