### ISSUE TITLE
[Android] ShapeSphere not selectable in 2.6.2

### ISSUE THREAD

**Issue by austindouglasgriffith** [mousebird-consulting-inc/WhirlyGlobe#1244]
Hello all,
It appears that tapping a ShapeSphere does not trigger the userDidSelect method in the Android 2.6.2 .aar file found [here](https://mousebird.github.io/WhirlyGlobe/builds/builds.html). 
The same feature is working appropriately in the iOS implementation, and it's used for a fairly critical piece of my application.
Would you be willing to address this issue?
Thank you for reading,
-Austin Griffith

**Comment by austindouglasgriffith** [comment]
I realized this problem is already acknowledged in a previous version [here.](https://github.com/mousebird/WhirlyGlobe/issues/718)
Would you like me to close this and leave a comment on the other one, or is this the appropriate place to discuss the issue?
Thank you again!
-Austin

**Comment by austindouglasgriffith** [comment]
Hello again, WhirlyGlobe team!
To clarify on my comment above, the problem itself is still unresolved. 

I’ve worked my way through the code a number of times, starting from processTap in GlobeController.java.
The processTap function calls userDidTap, rather than userDidSelect, when I tap a sphere; meaning getObjectsAtScreenLoc in MaplyBaseController.java is not returning the sphere’s ID.
After digging into getObjectsAtScreenLoc, the issue appears to be in pickObjects in SelectionManager.cpp.
I’m not sure if pickObjects ignores the spheres or is simply processing them incorrectly.
That is to say, addShapes in MaplyBaseController.java does indeed call addSelectableObject, just like addScreenMarkers does (I only say this because I know selection works for screen markers).
But I’ve reached a point where I’m not sure where else to dig.
Would anyone be able to provide assistance?

**Comment by mousebird** [comment]
What I'd probably do to sort this out is compare the path for selection on iOS vs. Android.  The core of it is C++ (SelectionManager), but perhaps it's not being added to the SelectionManager on Android.

**Comment by austindouglasgriffith** [comment]
That is correct, the stopping point appears to be on line 165 in SelectionManager.cpp, in addSelectableRectSolid
For some reason, getSelectID() on line 175 of ShapeManager.cpp is returning EmptyIdentity, causing the sphere to not be selectable. 
Does this give you any clues on where the issue might be?

**Comment by mousebird** [comment]
If we get a chance to look into it, then that is suggestive.

**Comment by austindouglasgriffith** [comment]
Huzzah! 
Adding the following lines to the beginning of the runnable in addShapes within MaplyBaseController.java has corrected this issue, for the most part. Spheres are now selectable, but only while within the boundaries of the globe, oddly enough. 
`for (Shape shape : shapes)
	shape.setSelectID(Identifiable.genID());`
Thank you for your guidance on this issue, Steve. 
I'm nearly willing to close the item, but I would prefer to also have sphere selection work when the sphere is outside the boundaries on the globe (as this is how it works on iOS). 
Are there any further tips you could share that would help me potentially resolve this last remaining piece?

**Comment by austindouglasgriffith** [comment]
Closing this item out as a duplicate: linked [here](https://github.com/mousebird-consulting-inc/WhirlyGlobe/issues/718)
