### ISSUE TITLE
Many metal command execution errors when UseHeaps=false

### ISSUE THREAD

**Issue by TimSylvester-mousebird** [mousebird-consulting-inc/WhirlyGlobe#1260]
"Execution of the command buffer was aborted due to an error during execution"

**Comment by mousebird** [comment]
This still the case?
Not that we'd ever turn heaps off at this point.

**Comment by TimSylvester-mousebird** [comment]
No, not seeing it with Xcode 13.2, with or without Metal frame capture and API validation.
