### ISSUE TITLE
MaplyShapeGreatCircle  is actually not great circle

### ISSUE THREAD

**Issue by coolDeven** [mousebird-consulting-inc/WhirlyGlobe#1271]
Why MaplyShapeGreatCircle is not great circle ?

I got `[-120,40]` and `[-80,40]` to draw a great circle . And I tried 3 methods.  Methods and images below :

1. Create `MaplyVectorObject` and set `subdivideToGlobeGreatCircle:0.0001`.   Red color attached. 

2. Split using "great circle algorithm", then I got a “geojson-string” which contains a group of points between point_1 and point_2 . Last step `MaplyVectorObject` created based on the “geojson-string”.  Blue color attached .

3. Create `MaplyShapeGreatCircle` object and set `kMaplyZBufferRead: @(NO)`.  Line is always shown in the globe even when it should behind the globe.  Green color attached .

In addition, I calculated the center between points using "great circle algorithm" to find out which line is more accurate，And attached a screen marker.

![image](https://user-images.githubusercontent.com/18394988/102334661-e6e9f200-3fc9-11eb-9ce6-47dcff92ab3f.png)

![image](https://user-images.githubusercontent.com/18394988/102334687-ee110000-3fc9-11eb-89de-cf3297b23a5d.png)

Comparing three methods mentioned before , I strongly doubt `MaplyShapeGreatCircle`  is actually not great circle. 

How to create a real great circle and draw accurately in WhirlyGlobe?

Could you please help with my questions ?

**Comment by mousebird** [comment]
This is very interesting.
One quick question.  Do you work for a company that's on support for the toolkit?

**Comment by mousebird** [comment]
And what version of the toolkit are you using?

**Comment by coderDeven** [comment]
> This is very interesting.
> One quick question. Do you work for a company that's on support for the toolkit?

Yes,  I am working for a company that's on support for WhirlyGlobe.

**Comment by coderDeven** [comment]
> And what version of the toolkit are you using?

Version  2.6.2

**Comment by mousebird** [comment]
2.6 is a bit out of date.  I don't recall that code is much different, though.  Any fixes would wind up in 3.0, though.
So hit me up via contact@mousebirdconsulting.com and let's see what we might need to do here.

**Comment by coderDeven** [comment]
> 2.6 is a bit out of date. I don't recall that code is much different, though. Any fixes would wind up in 3.0, though.
> So hit me up via [contact@mousebirdconsulting.com](mailto:contact@mousebirdconsulting.com) and let's see what we might need to do here.

OK, Thanks . I will contact you later .

**Comment by mousebird** [comment]
Tim, when you get a chance, let's look over our great circle calculation code.
I'm wondering if we should use that new library you roped in.

**Comment by TimSylvester-mousebird** [comment]
`MaplyGreatCircle` and `subdivideToGlobeGreatCircle` are great circles on a spherical earth model, which is what's used for display purposes, as the necessary view transforms can be done by OpenGL and Metal.  Users probably expect ellipsoidal calculations, e.g., WGS-84, which is now supported via `kMaplySubdivType: kMaplySubdivGreatCirclePrecise`, `subdivide(toGlobeGreatCirclePrecise:)`, and can be done manually through `GeoLibCalcDirectF`.  See `GreatCircleTestCase` in AutoTester.
