### ISSUE TITLE
Floating point precision loss

### ISSUE THREAD

**Issue by TimSylvester-mousebird** [mousebird-consulting-inc/WhirlyGlobe#1274]
Using `kMaplyVecCenterX/Y` and relative coordinates doesn't resolve precision problems which are particularly apparent on small (< 20m) circles.  A `MaplyShapeCircle` displays the same behavior, as does the location-accuracy circle.  Near lat=0/lon=0, the circles look good.

I came across this in `Circle::makeGeometryWithBuilder`, unfortunately `s/sinf/sin` and `s/float/double` didn't seem to make any difference.

`samples[ii] = xAxis * radius * sinf(2*M_PI*ii/(float)(sampleX-1)) + radius * yAxis * cosf(2*M_PI*ii/(float)(sampleX-1)) + dispPt;`

![CircleShape med](https://user-images.githubusercontent.com/71895881/103239442-5df48400-4902-11eb-9065-bff3abf82997.png)
![CircleShape small](https://user-images.githubusercontent.com/71895881/103239448-5fbe4780-4902-11eb-90f9-da1aa2f8b3a2.png)
![sampled small](https://user-images.githubusercontent.com/71895881/103239449-6056de00-4902-11eb-8c93-16b6e2a3c466.png)
![sampled+shape small near origin](https://user-images.githubusercontent.com/71895881/103239451-6056de00-4902-11eb-9655-ea60161d1f3d.png)
![sampled+shape small](https://user-images.githubusercontent.com/71895881/103239452-6056de00-4902-11eb-9d30-161c896f8b54.png)

**Comment by mousebird** [comment]
The shaders are using their matrix offsets a little differently.  This seems to help quite a bit.
