### ISSUE TITLE
iOS MaplyVectorObject Center is not accurate

### ISSUE THREAD

**Issue by zzjiong** [mousebird-consulting-inc/WhirlyGlobe#1275]
The location of MaplyVectorObject Center is not accurate, And the location is different from the Label  and Marker. In Develop branch.
![图片](https://user-images.githubusercontent.com/15756920/103396673-7cab8280-4b6f-11eb-8411-f0b835b3335b.png)
![图片](https://user-images.githubusercontent.com/15756920/103396685-87feae00-4b6f-11eb-8296-81e4d73cdc59.png)

**Comment by mousebird** [comment]
@TimSylvester-mousebird can you look at this one?  I thought of you since you last looked at this code.

**Comment by mousebird** [comment]
I wonder if this happens if you don't subdivideToGlobe?
Where does the center wind up?

**Comment by mousebird** [comment]
I set up a little test case and got much the same thing.

The problem I see is that we're calculating a center in lat/lon coordinates, but the display is either on the globe or on a spherical mercator based map.

Is this the flat map or the globe?

**Comment by zzjiong** [comment]
> I set up a little test case and got much the same thing.
> 
> The problem I see is that we're calculating a center in lat/lon coordinates, but the display is either on the globe or on a spherical mercator based map.
> 
> Is this the flat map or the globe?
on the globe

**Comment by mousebird** [comment]
Great, thanks!

So I believe that's the problem.  latitude / longitude vs spherical mercator.  In effect, the answer is "right", but it is not very useful.

**Comment by mousebird** [comment]
We have a separate set of methods to calculation these sorts of points now.
