### ISSUE TITLE
Unexpected buffer data types and structures in Metal functions due to nil argument

### ISSUE THREAD

**Issue by gregbuehler** [mousebird-consulting-inc/WhirlyGlobe#1281]
I'm having issues where nothing is rendered. After turning on additional debugging I found the following errors whenever anything is rendered:
```
2021-01-21 17:51:19.874711-0800 HelloWhirly[75397:7760608] Unexpected buffer data type in Metal Function vertexTri_multiTex
2021-01-21 17:51:19.874728-0800 HelloWhirly[75397:7760608] Unexpected buffer structure in Metal Function vertexTri_multiTex
2021-01-21 17:51:19.874824-0800 HelloWhirly[75397:7760608] Unexpected buffer data type in Metal Function fragmentTri_multiTex
2021-01-21 17:51:19.874885-0800 HelloWhirly[75397:7760608] Unexpected buffer structure in Metal Function fragmentTri_multiTex
```

The messages are being emitted from https://github.com/mousebird/WhirlyGlobe/blob/develop/ios/library/WhirlyGlobeLib/src/DrawableMTL.mm#L38-L45 as it appears `argInfo` is nil.

![image](https://user-images.githubusercontent.com/1753943/105443610-f986c500-5c20-11eb-9de8-f4735c80825e.png)

**Comment by mousebird** [comment]
What version of the toolkit this this?  Specifically what branch or commit?

**Comment by gregbuehler** [comment]
This is currently off the develop branch. Example project at https://github.com/gregbuehler/HelloWhirly.

**Comment by mousebird** [comment]
Not sure it's related, but I'd retain the Loader and the MBTiles fetcher somewhere.  Otherwise they might be released.

**Comment by gregbuehler** [comment]
Still seeing issues after rescoping the loader and tile sources outside of the function. Also attempted to use a remote tile source. I've updated the testbed project I was working from accordingly too. Also ruled out A14 processor weirdness by testing against an A9 iPad.

**Comment by mousebird** [comment]
It sort of looks like the Metal shaders are missing or somehow wrong.  Have you got the default metal file linked into your project directly?

**Comment by gregbuehler** [comment]
> It sort of looks like the Metal shaders are missing or somehow wrong. Have you got the default metal file linked into your project directly?

No? I'm not intimately familiar with the iOS build pipeline and the only integration steps I've done is to use the Podfile recommended in the tutorial with the addition of `use_frameworks!`.

**Comment by mousebird** [comment]
One common problem with Cocoapods is that the main project won't pick up the .metal file in the Pod.
You can work around it by finding the .metal file in the Pod and then adding it directly to your own project.  That seems to work around the problem.
