### ISSUE TITLE
[question] mapbox vector style example

### ISSUE THREAD

**Issue by petr-pokorny-1** [mousebird-consulting-inc/WhirlyGlobe#1283]
I am wondering if there is any sample showing how to use WhirlyGlobe library with mapbox vector tiles and styles?

**Comment by mousebird** [comment]
In the AutoTester apps for 3.0 there's a MapTiler example and a local vector MBTiles example.

**Comment by petr-pokorny-1** [comment]
Excellent, thank you!

**Comment by jimsonyang** [comment]
Good work!!
