### ISSUE TITLE
Pod Install Issues on iOS -- libjson not using https

### ISSUE THREAD

**Issue by Av3r3tt** [mousebird-consulting-inc/WhirlyGlobe#1285]
Hi, I just attempted to go through the tutorials for whirlyglobe for iOS using cocoapods and get the following terminal feedback:

`$ pod install
Analyzing dependencies
Pre-downloading: `WhirlyGlobe` from `https://github.com/mousebird/WhirlyGlobe.git`, branch `master`
Adding spec repo `trunk` with CDN `https://cdn.cocoapods.org/`
Downloading dependencies
Installing FMDB (2.7.5)
Installing KissXML (5.3.1)
Installing SMCalloutView (2.1.5)
Installing WhirlyGlobe (3.0)
Installing libjson (7.6.1)
Installing proj4 (4.8.0)

[!] Error installing proj4
[!] Unable to locate the executable `svn`

[!] 'libjson' uses the unencrypted 'http' protocol to transfer the Pod. Please be sure you're in a safe network with only trusted hosts. Otherwise, please reach out to the library author to notify them of this security issue.`

Just fyi.

**Comment by mousebird** [comment]
It looks like Xcode no longer installs SVN by default.
Take a look at this explanation.
https://stackoverflow.com/questions/60869347/mac-command-line-tools-11-4-no-longer-has-svn

**Comment by Av3r3tt** [comment]
> It looks like Xcode no longer installs SVN by default.
> Take a look at this explanation.
> https://stackoverflow.com/questions/60869347/mac-command-line-tools-11-4-no-longer-has-svn

Ah, that explains it, thanks!
