### ISSUE TITLE
Remove references to real-world width mode, which is no longer supported

### ISSUE THREAD

**Issue by TimSylvester-mousebird** [mousebird-consulting-inc/WhirlyGlobe#1291]
e.g., `WideVectorDrawableBuilder::setRealWorldWidth`

**Comment by yyakun** [comment]
hello, Is there an API that can be replaced?

**Comment by TimSylvester** [comment]
You can build a style that approximates a constant physical width, but there's no support for doing that automatically within the toolkit.
