### ISSUE TITLE
Choppy rendering performance on older iPad

### ISSUE THREAD

**Issue by dragonikpl** [mousebird-consulting-inc/WhirlyGlobe#1313]
https://user-images.githubusercontent.com/2223025/113278755-954c4580-92e2-11eb-89f8-567fc842f841.mov

Tested on https://everymac.com/systems/apple/ipad/specs/apple-ipad-9-7-inch-early-2017-wi-fi-only-specs.html

Tested using small map background (10 mb) and large (300 mb) - the same.
Application was compiled using `release` build in cocoapods and xcframework methods (the same result).

Here's the full code of main view controller:
```
class ViewController: UIViewController {

    let whirly = WhirlyGlobeViewController()
    var fetcher: MaplyMBTileFetcher!
    var loader: MaplyQuadImageLoader!
    
    var labelComponent: MaplyComponentObject?
    
    lazy var samplingParams: MaplySamplingParams = {
           let samplingParams = MaplySamplingParams()
           samplingParams.coordSys = fetcher!.coordSys()
           samplingParams.coverPoles = true
           samplingParams.edgeMatching = true
           samplingParams.minZoom = fetcher!.minZoom()
           samplingParams.maxZoom = fetcher!.maxZoom()
           samplingParams.singleLevel = true
           return samplingParams
       }()
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        // setup whirly
        addChild(whirly)
        view.addSubview(whirly.view)
        whirly.didMove(toParent: self)
        whirly.keepNorthUp = true
        
        // setup mbtile
        fetcher = MaplyMBTileFetcher(mbTiles: "geography-class_medres")!
        loader = MaplyQuadImageLoader(params: samplingParams, tileInfo: fetcher.tileInfo(), viewC: whirly)
        loader?.setTileFetcher(fetcher)
        
        // setup label
        let label = MaplyScreenLabel()
        label.text = "Hello world"
        label.loc = MaplyCoordinateMake(0, 0)
        labelComponent = whirly.addScreenLabels([label], desc: nil)
    }
}
```

**Comment by mousebird** [comment]
Can't really tell from the movie if it's a touch problem or a rendering problem.
Try the Animated test case and see what that looks like.

**Comment by dragonikpl** [comment]
Uploading IMG_0537_smaller.mov…

**Comment by dragonikpl** [comment]
Uploading animated_smaller.mov…

**Comment by dragonikpl** [comment]
Uploading IMG_0539_smaller.mov…

**Comment by dragonikpl** [comment]
We installed AutoTester on our iPad and the engine still behaves "choppy" - both in animated instances and just using the application. I can send you bigger files if you want, those were exported to being able to upload to github.

**Comment by mousebird** [comment]
I see similar problems on an iPad Air 2.  Looking into it.

**Comment by mousebird** [comment]
Do you have an earlier version that is faster?  Then I can compare it to see what's going on.

What often happens with Metal is that optimizations for newer devices will slow down things on old devices.  In this case it looks like heap management.

**Comment by dragonikpl** [comment]
WhirlyGlobe2 based on OpenGL works pretty good for us. Any other version that used Metal (and we had our build from October/November last year) seems to behave bad on older devices.

**Comment by mousebird** [comment]
Ah, so you weren't using an earlier Metal version.
There are a handful of devices where we can't use indirect rendering and that are very sensitive to some Metal optimizations.  We should be able to sort this out.

**Comment by mousebird** [comment]
Give the  topic/ipad-air-2-performance branch a try.
There's still more that can be done if needed, but I'd just like to get back to the GL level of performance for that device.

**Comment by dragonikpl** [comment]
Sorry for replying so late - I can just confirm that your changes did fix it on older iPad.

**Comment by mousebird** [comment]
Ah, good.  I'll merge that branch in at some point, then.

**Comment by andrewhoyer** [comment]
I was seeing some really slow tile loading and couldn't figure out what was happening, and I'm glad I found this thread. The side effect of Apple improving the way it handles older devices is that they become viable for much longer than you'd normally consider reasonable. I still use an iPad Air 2 for my everyday work and development testing. 

I'm going to follow this thread and will jump in for some testing once it's been merged into the main branch.

**Comment by mousebird** [comment]
We're merging it into develop.  Probably won't find its way into main for a few weeks.
