### ISSUE TITLE
xcode 12.5 fails to compile

### ISSUE THREAD

**Issue by bryan-heitman** [mousebird-consulting-inc/WhirlyGlobe#1340]
Issues with ScreenImportance.mm NSNull null] instead of [NSNull class] for isKindOfClass:

Also reporting it cannot include ScreenImportance.h (not found), not sure what is up with that one.

**Comment by geniomar** [comment]
I also tried to switch to the latest version and it complains saying _'WhirlyVector.h' file not found_ in GlobeTapMessage.h.

**Comment by mousebird** [comment]
Those are two separate issues in completely different branches.  Please open your own Issue.

**Comment by geniomar** [comment]
I apologize if I have created confusion. I was only trying to say that we could not overcome the original issue by pointing to a newer release.
I created a pull request with a one line fix that made me able to compile and run with both Xcode 12.4 and 12.5.

**Comment by mousebird** [comment]
Thanks for the pull request.  Fixed with the v2.6.7 tag.
