### ISSUE TITLE
Crash when loading MBTiles

### ISSUE THREAD

**Issue by dissymmetryoflift** [mousebird-consulting-inc/WhirlyGlobe#1354]
I've built from source. But when I try to load an MBTiles layer (code copied and pasted from tutorials) I'm getting:

"the offset into the buffer fragArgs that is bound at buffer index 2 must be a multiple of 256 but was set to 160."

This happens whether I use the MBTiles file provided in the tutorial, or my own. Any guidance?

**Comment by mousebird** [comment]
Which branch and on the device or simulator?

**Comment by mousebird** [comment]
That's what I was going to suggest next.  Sounds good.
