### ISSUE TITLE
Wide vector line rendering difference between Metal and OpenGL

### ISSUE THREAD

**Issue by TimSylvester-mousebird** [mousebird-consulting-inc/WhirlyGlobe#1356]
When rendered over dark imagery, a light "halo" becomes apparent on wide-vector lines:

![image](https://user-images.githubusercontent.com/71895881/117854703-9a37d980-b23e-11eb-9675-97a8db1ed22d.png)

On Android, the same lines blend better with the background:

![image](https://user-images.githubusercontent.com/71895881/117854822-b50a4e00-b23e-11eb-91e3-c265df683d02.png)

**Comment by mousebird** [comment]
Did you end up looking more at this?

**Comment by TimSylvester-mousebird** [comment]
I think this was resolved by the blend-mode changes in #1430.

<img src="https://user-images.githubusercontent.com/71895881/152080197-c9d29d2c-a9c8-4d9d-a61c-d1102eede7d7.png" width="500" />

**Comment by mousebird** [comment]
Thought so.  Cool.
