### ISSUE TITLE
How to change whold land color of globe

### ISSUE THREAD

**Issue by Miteshmakwana73** [mousebird-consulting-inc/WhirlyGlobe#1387]
Currently, it's showing like this 

![device-2021-06-28-161403](https://user-images.githubusercontent.com/38969602/123627323-7ac93000-d82f-11eb-8c44-369aa578081a.png)

i want to show red color instead of white how can i change that

is there any method or way? to customize the color of land and sea area

**Comment by mousebird** [comment]
That's part of your tile source.  You'd need to change the map you're using.

**Comment by Miteshmakwana73** [comment]
@mousebird didn't understand can you explain what code I have to change? or example

**Comment by mousebird** [comment]
The colors are in your tile source.  You might be able to achieve something by changing the color on the QuadLoader.

**Comment by Miteshmakwana73** [comment]
@mousebird you mean i need to change in the .mbtiles file? right?

**Comment by mousebird** [comment]
That does not look like Geography Class to me.  But if you're using an MBTiles file, then you need to change that, yes.

**Comment by Miteshmakwana73** [comment]
no, i am not using mbtiles file i just see example from the [website](https://mousebird-consulting-inc.github.io/WhirlyGlobe/tutorial/android/local-image-layer.html) 

is there any example to how can i change land color? because i didn't find anything in `QuadImageLoader`

i am doing something like this

 ```
// Set up an image loader, tying all the previous together.
        val loader = QuadImageLoader(params, tileInfo, baseControl)

        loader.setImageFormat(RenderController.ImageFormat.MaplyImageUShort565)
```

**Comment by mousebird** [comment]
Where are you getting your image tiles?  That's the source you need to change.

**Comment by Miteshmakwana73** [comment]
@mousebird 
i am getting tile image from here

`val tileInfo = RemoteTileInfoNew("http://tile.stamen.com/toner-background/{z}/{x}/{y}.png", 0, 18) `

**Comment by mousebird** [comment]
Got it.  So you need a different tile source.

**Comment by Miteshmakwana73** [comment]
@mousebird yes currently it's in white color my requirement is to get this tile in red color

**Comment by mousebird** [comment]
You can try setting the color on the QuadLoader, but if that doesn't work then you need a different tile source.
We don't provide tile sources.  This is something you have to do yourself.

**Comment by Miteshmakwana73** [comment]
@mousebird 

Do you have any example or how can i use `QuadLoader`  in app because i didn't find anything about quadloader in demo or website.

**Comment by mousebird** [comment]
The QuadImageLoader.  It's in the code you pasted into this thread.
Look at the methods on the QuadImageLoader.   There's one for color.

**Comment by Miteshmakwana73** [comment]
@mousebird thank you for your support your solution is working on IOS but in android getting crash while calling setColor method of QuadImageLoader

```
var mColor = 0
 override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
        super.onViewCreated(view, savedInstanceState)
        mColor = ContextCompat.getColor(context!!, R.color.red)
    }
```

inside controlHasStarted method i write this

```
// Set up an image loader, tying all the previous together.
        val loader = QuadImageLoader(params, tileInfo, baseControl)

        loader.setImageFormat(RenderController.ImageFormat.MaplyImageUShort565)
        loader.setColor(mColor)
```
this is what i am getting in logcat i mean i didn't pass any null value still getting this error

```

2021-07-12 11:18:59.985 9518-9518/com.tops.globemap E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.tops.globemap, PID: 9518
    java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.lang.ref.WeakReference.get()' on a null object reference
        at com.mousebird.maply.QuadImageLoaderBase.setColor(QuadImageLoaderBase.java:107)
        at com.tops.globemap.fragment.HelloGlobeFragment.controlHasStarted(HelloGlobeFragment.kt:103)
        at com.mousebird.maply.GlobeMapFragment$1.run(GlobeMapFragment.java:83)
        at com.mousebird.maply.BaseController$2.run(BaseController.java:945)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

**Comment by mousebird** [comment]
Good catch.  Fixed on the develop branch.

**Comment by Miteshmakwana73** [comment]
@mousebird 
From where i can download new .aar file in website it's showing last Version 3.3 which i am already using.

Last time i downloaded from here

**Comment by mousebird** [comment]
When the CI system catches up, it should pop up on that page under develop.  Hard to tell when that happens, though.  Maybe look at the date on the AAR.
