### ISSUE TITLE
Android 3.2 : Shape color flashing on and off as the globe is moved around

### ISSUE THREAD

**Issue by austindouglasgriffith** [mousebird-consulting-inc/WhirlyGlobe#1402]
Hello WhirlyGlobe team,

In upgrading from 2.6 to 3.2, I have encountered an issue wherein the colors of my ShapeSpheres repeatedly flash between white and then back to their original color.

This impacts all of my Shapes simultaneously, flickering on & off as the user moves the globe around.

A video of the behavior can be found [here](https://drive.google.com/file/d/1Ew9c0DP4dRDXAPac40m7ibzA_OqNqLGh/view?usp=sharing).

This can also be observed in the AutoTesterApp in the 'Shape Test Case', where it impacts some of the Spheres & Cylinders present.

As Android 2.6 did not contain ShapeLinear, this means I'm not able to bring my Android app up to par with the iOS version.

Please let me know if I can be of any assistance in finding a resolution. 
Thank you!
-Austin

**Comment by austindouglasgriffith** [comment]
During the testing process I found that adding a ShapeLinear causes this issue to not occur for any spheres added after having added the ShapeLinear. 
As a workaround, I have added a function to create a ShapeLinear and called the function early in my ControlHasStarted Override. 
The function is listed below, for anyone else who runs into this issue. Hopefully it will also help in finding a proper solution. 
`    public void addLinearWorkaround(){
        ShapeLinear line = new ShapeLinear();
        Point3d prevCoord = new Point3d();
        Point3d thisCoord = new Point3d();
        prevCoord.setValue(0,0,0);
        thisCoord.setValue(0,0,0);
        Point3d[] coords = {prevCoord,thisCoord};
        line.setCoords(coords);
        List<Shape> shapes = new ArrayList<>();
        shapes.add(line);
        ShapeInfo shapeInfo = new ShapeInfo();
        Shader shader = globeControl.getShader(Shader.NoBackfaceLineShader);//xxx
        shapeInfo.setShader(shader);
        shapeInfo.setColor(0.5f, 0.5f, 0.5f, 1f);
        shapeInfo.setDrawPriority(1000000);
        globeControl.addShapes(shapes, shapeInfo, GlobeController.ThreadMode.ThreadAny);
    }`

**Comment by TimSylvester-mousebird** [comment]
This turns out to be caused by a low-level bug, and that work-around may not be reliable as it depends on the order in which the drawables are processed.  The good news is that the fix is simple, and will probably also fix some odd behavior in other cases.  See PR #1443.
