### ISSUE TITLE
Android 3.2 : ShapeLinear rendered as 2D entity while in 3D WhirlyGlobe mode

### ISSUE THREAD

**Issue by austindouglasgriffith** [mousebird-consulting-inc/WhirlyGlobe#1403]
Hello WhirlyGlobe team,

In the latest edition of the Android library, I've encountered an issue with the implementation of ShapeLinear. 

The lines created by ShapeLinear all appear in the globe's equatorial plane, as though they're being rendered in a 2D Maply environment rather than in a 3D WhirlyGlobe instance. 

The issue can be seen on Android [here](https://drive.google.com/file/d/14TkAbpyZ-i5YLU1VtZw_9cgKpiyKP3pd/view?usp=sharing) (Compared to the expected behavior on iOS, shown [here](https://drive.google.com/file/d/1KLUVTopSOI7wSGsS2HfAMUGoA57SiuOg/view?usp=sharing))
The color flashing issue is presumably separate, and is ticketed [here](https://github.com/mousebird-consulting-inc/WhirlyGlobe/issues/1402). 

This cannot be observed in the AutoTesterApp, as it does not use ShapeLinear. 

This also implies I'm not able to bring my Android app up to par with the iOS version :(
Please let me know if I can be of any assistance in finding a resolution.
Thank you!
-Austin

**Comment by austindouglasgriffith** [comment]
I was given the tip that this may be related to the Shader being applied to the shape, but that ended up being irrelevant. 
Currently I think the issue is related to the VectorType property being applied to ShapeLinear while using MapDisplayType.Globe. 

There's four different vector types mentioned that I can see; VectorLinear, VectorLinear3d, VectorAreal, & VectorPoints.
Not sure if it's applying the wrong type when the shape is created, if it's retrieving it incorrectly, or something else entirely. 
MaplyGreatCircle, which appears to use ShapeLinear under the hood, functions as expected (meaning whichever vector type should be used at least _can_ be used).

Would greatly appreciate any thoughts on if I'm headed in the right direction. 
Happy to discuss payment if that's what's required. 
I've lost a fair amount of hair on this, hah :)

**Comment by austindouglasgriffith** [comment]
Further testing has led me to believe this issue is related to how I'm generating the Point3D entities being passed into my ShapeLinear, and the coordinate system they're being made in. 
I've made an absolutely hacktastic workaround in which I highjack GreatCircle and use it in place of ShapeLinear; given that the Point3D creation is taken care of in the C++ native portion of the library, by a function called SampleGreatCircle. 
I set the Height value to be constant in this function, rather than the parabola that it typically creates. 
Then I use small chunks of GreatCircle to make the trajectory vectors I intended to display. 
This results in small disconnected segments while presenting any elliptical orbits, but I consider this sufficient as I've given up on this issue. 
I hope this helps any other poor soul who finds themselves in a similar circumstance!

**Comment by TimSylvester-mousebird** [comment]
The problem here is that Android is missing a conversion from geo coordinates to model/display coordinates in the JNI layer that's being done on iOS as part of the ObjC layer.  To get correct results, you would have needed to pass in display coordinates, in which (0,0,0) is the center of the earth, (1,0,0) is the north pole, for example, but there are no Java APIs to convert between geo and these coordinates.

Your workaround is leveraging the fact that Great Circles do this conversion as part of sampling the GC into a linear.  

This should be resolved by PR #1442, and linears are now included in the shapes test cases.
