### ISSUE TITLE
Removing markers and labels from globe

### ISSUE THREAD

**Issue by harikrishna-daraji** [mousebird-consulting-inc/WhirlyGlobe#1405]
Hello Team,
I am adding markers and labels in the globe  like this:
<img width="1020" alt="Screen Shot 2021-07-13 at 3 20 38 PM" src="https://user-images.githubusercontent.com/65469425/125512658-0a7e189e-eeec-4ecb-8476-ca817d9a7704.png">

but I do not find any methods to remove them, kindly suggest something.

**Comment by mousebird** [comment]
Those methods return a MaplyComponentObject.
Keep track of it and then call removeComponentObject(s)
