### ISSUE TITLE
how could i remove screenMarks or ScreenLabels? if  i have already add screenMarks or add screenLabels

### ISSUE THREAD

**Issue by zhujianyang** [mousebird-consulting-inc/WhirlyGlobe#1419]
version:2.6.5
and how could i custom a view as a screenMarker ？

**Comment by mousebird** [comment]
When you add screen markers you get a ComponentObject back.  You can pass that ComponentObject to a remove method in the controller.

I assume you mean Android.  There is no way to make a View a ScreenMarker.
