### ISSUE TITLE
iOS  There is a memory leak on the iPad air 4 

### ISSUE THREAD

**Issue by zzjiong** [mousebird-consulting-inc/WhirlyGlobe#1423]
The memory keeps growing while sliding, with GeographyClassTestCase, In develop branch.
<img width="1656" alt="截屏2021-08-19 下午4 23 48" src="https://user-images.githubusercontent.com/15756920/130171783-23785850-3962-49a6-8b9b-958a95710863.png">

**Comment by mousebird** [comment]
For GeographyClass in 3.x I see it level off at about 190MB.
<img width="971" alt="Screen Shot 2021-09-08 at 11 09 23 AM" src="https://user-images.githubusercontent.com/1040005/132562069-0da6c44f-2ca7-4de4-b4bd-1666bb7ed04d.png">

What device is this?  The toolkit uses different Metal rendering techniques for older devices.

**Comment by mousebird** [comment]
I tried it with direct rendering.  Levels off a bit higher.
<img width="1005" alt="Screen Shot 2021-09-08 at 11 12 41 AM" src="https://user-images.githubusercontent.com/1040005/132562625-3d386100-2bc6-4d22-bc2a-99fc5bcd66a8.png">

**Comment by zzjiong** [comment]
> For GeographyClass in 3.x I see it level off at about 190MB. <img alt="Screen Shot 2021-09-08 at 11 09 23 AM" width="971" src="https://user-images.githubusercontent.com/1040005/132562069-0da6c44f-2ca7-4de4-b4bd-1666bb7ed04d.png">
> 
> What device is this? The toolkit uses different Metal rendering techniques for older devices.

iPad air 4
