### ISSUE TITLE
Unable to install with Cocoapods

### ISSUE THREAD

**Issue by billburgess** [mousebird-consulting-inc/WhirlyGlobe#1424]
There are a couple of issues when installing with Cocoapods.

- No backwards compatibility with versions. The only version I can get to install is v2.6.7.
- v2.6.7 installs v2.6.5
- `#import <WhirlyGlobe.h>` is erroring with `'WhirlyGlobe.h' file not found` in WhirlyGlobeViewController_private.h

We are not able to take the 3.0 update of WhirlyGlobe as of yet and are trying to migrate away from Carthage to Cocoapods. Is this a known issue or am I doing something wrong? Any help would be appreciated.

### Podfile
`pod 'WhirlyGlobe', :git => 'https://github.com/mousebird/WhirlyGlobe.git', :tag => 'v2.6.7'`

Thanks in advance.

**Comment by mousebird** [comment]
The 2.x branch should be up to date, but Cocoapods is always a bit weird.
In general you want to avoid pulling in the private header files unless you need them.  I'd look to your pod settings to see if that might be triggered.
Bridging headers can also be an issue if you have mixed ObjC/Swift.

The quickest way to solve this is to get on support and we'll sort it out for you.

**Comment by billburgess** [comment]
I'm not familiar with support for it, do you have a link for that? Thanks!

**Comment by mousebird** [comment]
I know someone at Appareo knows what support is, but email me direct and I'll send you the info.  contact@mousebirdconsulting.com

**Comment by billburgess** [comment]
I think this error was incorrectly attributed to the library. There is a separate issue that I will create as a follow on for something separate. The issue here was related to proper inheritance with Cocoapods.
