### ISSUE TITLE
Error around angled brackets includes

### ISSUE THREAD

**Issue by billburgess** [mousebird-consulting-inc/WhirlyGlobe#1426]
When installing via Cocoapods, v1.10.2, library version 2.6.7, the project fails to to compile with the error:

`'WhirlyGlobe.h' file not found with <angled> include; use "quotes" instead`

This error shows up on every single `#import <WhirlyGlobe.h>` in the application. This is a known issue for Xcode 12 and can normally be mitigated by setting the `CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER` to NO for the Pods project. I have done this and the error is still showing up.

I have tested the fix by switching the imports to use quotes and the project compiles fine. Is there any way to put a small PR in against version 2.6.7 that converts these imports to use quotes instead? Or is there a fix I'm not seeing?

**Comment by mousebird** [comment]
If that's a workaround, then great.  It makes me suspect there's something more fundamental going on, like headers being imported where they shouldn't.  Indeed, I'm not really sure why your own app needs to be seeing WhirlyGlobe.h at all.

If this turns up with a support customer, we'll take a look.  Until then, I'll wish you luck.
