### ISSUE TITLE
the cacheDir not work in iOS

### ISSUE THREAD

**Issue by hellobinbin** [mousebird-consulting-inc/WhirlyGlobe#1428]
I add three  MaplyQuadImageTilesLayer to WhirlyGlobeViewController;
then I set the three different cacheDir of MaplyRemoteTileSource；
then set  AutoRotate
  [theViewC setAutoRotateInterval:2 degrees:0.5];
but the cacheDir not work;
always refresh the layer！

**Comment by mousebird** [comment]
If the cache directory exists, it should just store the files there.
I'd suggest stepping down into the caching logic to see what it's doing.
