### ISSUE TITLE
iOS 3.3 binary execution error: dyld: Library not loaded:

### ISSUE THREAD

**Issue by xmercade** [mousebird-consulting-inc/WhirlyGlobe#1432]
I've followed the HelloEarth tutorial with the latest binary available (WhirlyGlobe_Maply_Distribution_3_3) and I always get the same error just few seconds after launching the app either in a real device or a simulator:

`"dyld: Library not loaded: @rpath/WhirlyGlobeMaplyComponent.framework/WhirlyGlobeMaplyComponent
  Referenced from: /private/var/containers/Bundle/Application/F883B2A0-5588-420D-8DA1-3B8A6A7E7B2B/HelloEarth.app/HelloEarth
  Reason: image not found
dyld: launch, loading dependent libraries
DYLD_LIBRARY_PATH=/usr/lib/system/introspection
DYLD_INSERT_LIBRARIES=/Developer/usr/lib/libBacktraceRecording.dylib:/Developer/usr/lib/libMainThreadChecker.dylib:/Developer/Library/PrivateFrameworks/DTDDISupport.framework/libViewDebuggerSupport.dylib"`

By default the framework is added to the project with Embed mode "Do not embed", if I leave it as it is I get the previous error. 
If I change it to mode "Embed & Sign" or "Embed without signing" then I get the following compilation error: 

`Building for iOS, but the linked and embedded framework 'WhirlyGlobeMaplyComponent.framework' was built for iOS + iOS Simulator.
`

No matter the target device, real one or simulator, I get this compilation error if I try to embed the library.
I've tried it with both Swift and Obj-C approaches with no luck. Any idea on how to solve this and make it run?

Currently using Xcode 12.5.1 and iOS 14.5 as target OS.

**Comment by TimSylvester-mousebird** [comment]
I don't know about `libBacktraceRecording.dylib` and `libMainThreadChecker.dylib`, but I would try disabling the diagnostic options in the scheme setup. 

The framework error is because we're using an old format for the framework.  The issue is detailed here, along with a workaround:

https://stackoverflow.com/a/65315026/135138

**Comment by xmercade** [comment]
That worked, as said in that discussion, seems that Apple force us to move to use .xcframeworks.
Many thanks for the quick answer!
