### ISSUE TITLE
addVectors issues

### ISSUE THREAD

**Issue by ForTraces** [mousebird-consulting-inc/WhirlyGlobe#1435]
Hello
When I use addVectors to draw a closed area, When setting the transparency is very small, the transparency does not work
My code is:
 NSDictionary *vecDict = @{ 
        kMaplyColor:[UIColor colorWithRed:1 green:97/255 blue:116/255 alpha:0.1],
        kMaplyFilled: @YES,
        kMaplyDrawPriority: @(kMaplyVectorDrawPriorityDefault + 1000),
        kMaplyVecWidth: @(1)
    };
   MaplyVectorObject *vec = [self _buildVectorObjectByDatas:models];
    [self.baseViewC addVectors:@[vec] desc:vecDict mode:MaplyThreadCurrent];

**Comment by mousebird** [comment]
What are you expecting it to do?

**Comment by ForTraces** [comment]
I set a very low transparency, but the transparency of the drawing is not very transparent
<img width="185" alt="WeChatf944b09fe383bc4dbf35c0c62deb270e" src="https://user-images.githubusercontent.com/8295724/132608696-d222c426-045f-4ee5-b8e7-403d96b0b3ad.png">

**Comment by ForTraces** [comment]
I set the transparency to 0.1, but the red painted is still very heavy and there is no obvious transparency effect

**Comment by mousebird** [comment]
You need to multiply the transparency through the rest of the color.

**Comment by ForTraces** [comment]
Can you elaborate on how to do it.

**Comment by ForTraces** [comment]
I set black on the bottom and red on the top, and the red transparency effect is not seen
<img width="636" alt="图片" src="https://user-images.githubusercontent.com/8295724/133064422-20c58b59-998c-4b32-afe2-96964e1048ff.png">
<img width="266" alt="图片" src="https://user-images.githubusercontent.com/8295724/133064962-126da365-6d98-4cdf-90a2-fae6a716cf78.png">

**Comment by mousebird** [comment]
In the example at the top you were specifying each RGB and A component.  Multiply the R, G, and B by the alpha value.

**Comment by ForTraces** [comment]
The problem is solved, thank you very much
