### ISSUE TITLE
The runway should stick to its place.

### ISSUE THREAD

**Issue by vaibhavidvt** [mousebird-consulting-inc/WhirlyGlobe#1438]
I reference the AutoTester Runwaybuilder test cases and create a runway on the map, but when we move the map runway move as well from its should stick to its place, I hope you got my point, Please check the attached video.

https://user-images.githubusercontent.com/75068296/133589108-a5e054d6-d98e-4072-a1fb-0ad2280ade83.mov

**Comment by mousebird** [comment]
Looks like the runway and the screen marker are at different elevations.
Aviation apps tend to require a bit more precision.  You should strongly consider paying for support.

**Comment by vaibhavidvt** [comment]
Thank you, Steve, I have changed the elevation matrix, now it's fixed.
