### ISSUE TITLE
Runtime error running iOS 3.3 binary on simulator

### ISSUE THREAD

**Issue by xmercade** [mousebird-consulting-inc/WhirlyGlobe#1439]
I'm working on a test project starting from HelloEarth tutorial with the latest binary available (WhirlyGlobe_Maply_Distribution_3_3).
I've already built the .xcframework as suggested in a previous issue and I'm able to run everything (custom tiles, boundaries, etc...) without problems on a device, but when I try to run it on any simulator I'm getting the following error:

`Compiler failed to build request
newArgumentEncoder:84: failed assertion 'Function vertexLineOnly_flat does not have a buffer argument with buffer index 14'
newArgumentEncoder:84: failed assertion 'Function vertexLineOnly_flat does not have a buffer argument with buffer index 14'
CoreSimulator 776.1 - Device: iPad Pro (9.7-inch) (5187418F-29EA-4914-B92F-203375B6D4AF) - Runtime: iOS 14.5 (18E182) - DeviceType: iPad Pro (9.7-inch)`

I tried disabling Metal API Validation in the scheme configuration, but it doesn't work either and then the error is:

`-[_MTLFunction newArgumentEncoderWithBufferIndex:reflection:functionReflection:], line 6872: error 'bufferIndex 14 does not identify an argument buffer'
-[_MTLFunction newArgumentEncoderWithBufferIndex:reflection:functionReflection:]:6872: failed assertion 'bufferIndex 14 does not identify an argument buffer'
-[_MTLFunction newArgumentEncoderWithBufferIndex:reflection:functionReflection:]:6872: failed assertion 'bufferIndex 14 does not identify an argument buffer'
CoreSimulator 776.1 - Device: iPad Pro (9.7-inch) (5187418F-29EA-4914-B92F-203375B6D4AF) - Runtime: iOS 14.5 (18E182) - DeviceType: iPad Pro (9.7-inch)`

I googled around for hours but I'm not able to see what could be wrong. I've double checked that each source frameworks of the final .xcframework contain only the desired archs (the first arm64 and x86_64 the second).
Anyone have any clue on what could be happening?

**Comment by mousebird** [comment]
The simulator isn't very reliable with Metal.  It's gotten better with recent versions, but it's still not 100% and you'll get weird stuff like this.
