### ISSUE TITLE
iOS pod install issue

### ISSUE THREAD

**Issue by HuaYunZhangKe** [mousebird-consulting-inc/WhirlyGlobe#1441]
When I try to use the command 'pod install', the terminal told me that.

Analyzing dependencies
Pre-downloading: `WhirlyGlobe` from `https://github.com/mousebird/WhirlyGlobe.git`, branch `master`
Downloading dependencies
Installing FMDB (2.7.5)
Installing KissXML (5.3.1)
Installing SMCalloutView (2.1.5)
Installing WhirlyGlobe (3.2)
Installing libjson (7.6.1)

[!] Error installing libjson
[!] /usr/bin/unzip /var/folders/wj/v1x1f22x1ms9g06hxkbs4c4h0000gn/T/d20210925-1170-i05e9u/file.zip -d /var/folders/wj/v1x1f22x1ms9g06hxkbs4c4h0000gn/T/d20210925-1170-i05e9u

Archive:  /var/folders/wj/v1x1f22x1ms9g06hxkbs4c4h0000gn/T/d20210925-1170-i05e9u/file.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of /var/folders/wj/v1x1f22x1ms9g06hxkbs4c4h0000gn/T/d20210925-1170-i05e9u/file.zip or
        /var/folders/wj/v1x1f22x1ms9g06hxkbs4c4h0000gn/T/d20210925-1170-i05e9u/file.zip.zip, and cannot find /var/folders/wj/v1x1f22x1ms9g06hxkbs4c4h0000gn/T/d20210925-1170-i05e9u/file.zip.ZIP, period.

[!] 'libjson' uses the unencrypted 'http' protocol to transfer the Pod. Please be sure you're in a safe network with only trusted hosts. Otherwise, please reach out to the library author to notify them of this security issue.

**Comment by mousebird** [comment]
That looks like a transitory error of some sort.  Does it happen consisently?

**Comment by akovalov** [comment]
Looks like `master` branch does not link to the latest version and tutorial at https://mousebird-consulting-inc.github.io/WhirlyGlobe/tutorial/ios/building_from_cocoapod.html has an old repo url. 
As for today the latest version is v3.4 so I am using the following in CocoaPods
```
pod 'WhirlyGlobe', :git => 'https://github.com/mousebird-consulting-inc/WhirlyGlobe.git', :tag => 'v3.4'
```

**Comment by akovalov** [comment]
`#import <map>` in `ActiveModel.h` causes build error `'map' file not found` when build with CocoaPods from main branch.
Would be appreciated if have any ideas how to fix that. Thank you!

**Comment by akovalov** [comment]
An update is here https://github.com/mousebird-consulting-inc/WhirlyGlobe/pull/1455
