### ISSUE TITLE
[iOS 3.4] Fade in/out not working properly

### ISSUE THREAD

**Issue by ldomaradzki** [mousebird-consulting-inc/WhirlyGlobe#1457]
When using `kMaplyFade` with 2 second timer I get this result (which is ok):

https://user-images.githubusercontent.com/4224034/137270429-a28f293e-1b5e-441b-878f-5bb6ac3028a2.mov

When I use `kMaplyFadeIn` I don't see any fading:

https://user-images.githubusercontent.com/4224034/137270522-552e4477-140d-4236-9622-91a12ce49b81.mov

The same is with `kMaplyFadeOut` - no fading visible:

https://user-images.githubusercontent.com/4224034/137270599-db6ee968-fa1f-4f06-9794-7f2664c21204.mov

I did not use `kMaplyFadeInTime` and `kMaplyFadeOutTime` (what do they do exactly?)

**Comment by TimSylvester-mousebird** [comment]
This should be resolved in develop.
