### ISSUE TITLE
MaplyQuadImageTilesLayer After removing the loading tiles, a white flash will appear

### ISSUE THREAD

**Issue by ForTraces** [mousebird-consulting-inc/WhirlyGlobe#1459]
MaplyRemoteTileSource *tileSource = [[MaplyRemoteTileSource alloc] initWithBaseURL:url ext:nil minZoom:0.0005 maxZoom:19];

    tileSource.cacheDir = thisCacheDir;
    MaplyQuadImageTilesLayer *layer = [[MaplyQuadImageTilesLayer alloc]
                                       initWithCoordSystem:tileSource.coordSys tileSource:tileSource];
    layer.handleEdges = YES;
    layer.coverPoles = YES;
    layer.drawPriority = kMaplyImageLayerDrawPriorityDefault + pri;
    layer.numSimultaneousFetches = 8;
    [self.baseViewC addLayer:layer];

<img width="438" alt="WeChat976c419e48b28d27048fb58494840f73" src="https://user-images.githubusercontent.com/8295724/139663175-babef626-cabf-4256-8ef8-12d46c90fc9c.png">

**Comment by mousebird** [comment]
Sorry, that doesn't give me much information.
And that's a pretty old version of the toolkit.

**Comment by ForTraces** [comment]
version: 2.6.2   a white background will appear when loading remote tiles, and it will disappear after loading.

**Comment by mousebird** [comment]
I'm afraid I haven't seen that one before.
