### ISSUE TITLE
'invariant' attribute requires Metal language standard ios-metal2.1 or higher

### ISSUE THREAD

**Issue by bbalabanli** [mousebird-consulting-inc/WhirlyGlobe#1460]
Just updated xcode Version 13.1, and tried to build the whirlyglobe master branch and  it gives the following error while building.

The ipad version is ios 15+ and deployment target is the same. Is there known issue about this one?

"../Pods/WhirlyGlobe/ios/library/WhirlyGlobeLib/include/DefaultShadersMTL.h:315:23: 'invariant' attribute requires Metal language standard ios-metal2.1 or higher"

**Comment by mousebird** [comment]
Just set the Metal version to 2.1 in the project.

**Comment by bbalabanli** [comment]
Can you add it to tutorial ?

**Comment by akovalov** [comment]
When install WhirlyGlobe via CocoaPods the generated `Pods.xcodeproj` does not have set `Metal Language Revision`. 
So need to set it manually as on the screenshot. 

<img width="1045" alt="Screenshot 2022-01-17 at 11 25 13" src="https://user-images.githubusercontent.com/9693643/149743565-a050605a-68a9-48a3-b854-2f36b82417c6.png">

However, on each `pod install` the `Pods.xcodeproj` will be regenerated without this setting. 
Add the following at the end of your `Podfile`:

```
post_install do |installer|
  installer.pods_project.build_configurations.each do |config|
    config.build_settings['MTL_LANGUAGE_REVISION'] = 'Metal21'
  end
end
```

Please keep in mind that Metal section in Xcode Build Settings will appear only if project has f `.metal` file. In my case my project doesn't have metal files so Metal build settings section appear only in `Pods.xcodeproject`. If you have metal in your project you need to set Metal version (like on the screenshot) in your project as well.

**Comment by akovalov** [comment]
Didn't manage framework to work via CocoaPods. An update is here https://github.com/mousebird-consulting-inc/WhirlyGlobe/pull/1455
