### ISSUE TITLE
Building for iOS, but the linked and embedded framework 'WhirlyGlobeMaplyComponent.framework' was built for iOS + iOS Simulator.

### ISSUE THREAD

**Issue by bbalabanli** [mousebird-consulting-inc/WhirlyGlobe#1463]
Despite showing binary reference to the framework it gives the error framework is built for simulator.

**Comment by akovalov** [comment]
@bbalabanli see https://github.com/mousebird-consulting-inc/WhirlyGlobe/pull/1455
