### ISSUE TITLE
ScreenLabel  display error 

### ISSUE THREAD

**Issue by RookieFeng** [mousebird-consulting-inc/WhirlyGlobe#1464]
Hi, Steve :
I am trying to integrate WhirlyGlobe-3.4 into my project. During this process, I encountered some problems. Yes, I need your help.
The font size and text color displayed by ScreenLable are not the same as the values I set, which looks strange.
Here is a screenshot:

![image](https://user-images.githubusercontent.com/52650897/141228845-ed861f27-30c0-4ed2-bae3-c97d5b34555b.png)

All ScreenLabel have this problem, could you help me solve this problem ?

**Comment by mousebird** [comment]
iOS or Android?

**Comment by RookieFeng** [comment]
It's a bit embarrassing~, I checked the code carefully and found that my code has a bug, which caused this problem. Thanks anyway .  I'll close this issue.
