### ISSUE TITLE
MaplyMBTileFetcher does not view errror Blackscreen

### ISSUE THREAD

**Issue by bbalabanli** [mousebird-consulting-inc/WhirlyGlobe#1465]
No any xcode output gives error after device built there is empty screen app launches and no other error given. Debug is successful as well. What can be the problem?(maps and resources everyting is good)

**Comment by mousebird** [comment]
There isn't enough information here to tell what's going on.
I'd suggest trying to build and run the AutoTester app and replicate your problem with one of the tests.
