### ISSUE TITLE
vector memory usage not released after removeObjects

### ISSUE THREAD

**Issue by RookieFeng** [mousebird-consulting-inc/WhirlyGlobe#1467]
Hi , Steve 
	WhirlyGlobe 3.4 seems to have memory issues. When I use MaplyComponentObject to remove the WideVector, I found that the vector just disappeared from the screen, but the actual memory usage was not released. It’s may be "abandoned memory".
The memory will not grow endlessly, and after sliding many times, it will stabilize at a  number .
Below is a brief test code.
Each time the Globe slides, draw a set of vectors or remove the vector drawn at the end of the previous slide.

-(void)globeViewController:(WhirlyGlobeViewController *)viewC didStopMoving:(MaplyCoordinate *)corners userMotion:(bool)userMotion{
     static int tag = 0;
     tag ++;
     if(tag% 2 == 0){
         // remove all the vectors created before
         if(self.objArray.count){
             [viewC removeObjects:self.objArray mode:MaplyThreadCurrent];
         }
         [self.objArray removeAllObjects];
         self.objArray = nil;
         return;
     }
     // add one set of vector (one single vector have thousands of points)
     self.objArray = [self addVectorsToViewC:viewC];  
}

Memory Use : 
![image](https://user-images.githubusercontent.com/52650897/142378867-ffcc3c03-699a-4677-a2db-d4ad56e61043.png)

**Comment by RookieFeng** [comment]
If WideVector is added to Globe with the kMaplyWideVecImplPerf property, memory will drop after WideVector is removed (removeObject). But the attribute kMaplyWideVecImplPerf will make the Vector generated by texture lose its display style.

**Comment by mousebird** [comment]
If memory use is stabilizing then it's likely to be the Metal heaps in the renderer.
That's normal.  It's only if memory usage continues upward indefinitely that it might be a problem.

**Comment by RookieFeng** [comment]
I did a lot of testing again. In fact, it is doing one thing: "Each time the scroll ends, draw a set of WideVector and remove the WideVector drawn in the last scroll."

When drawing a large number of vectors, scrolling and zooming will become unsmooth. At this time,
By quickly dragging or zooming the Globe, the memory will explode. Until an OOM crash occurs.

So ,  I  think it's  a  problem.

**Comment by TimSylvester-mousebird** [comment]
I'm seeing completely stable memory utilization across thousands of add/remove operations of wide vectors using both the default and performance implementations.

Can you provide a test case that demonstrates the issue?

<img src="https://user-images.githubusercontent.com/71895881/151900003-406d6afe-1d11-49c5-8aae-d43e06d7cc34.png" width="500"/>
