### ISSUE TITLE
Screen label can not be removed because of `layoutVec`

### ISSUE THREAD

**Issue by RookieFeng** [mousebird-consulting-inc/WhirlyGlobe#1469]
I created a areal vector and a label . And set the `layoutVec` to the screen label . 
Image below :

![image](https://user-images.githubusercontent.com/52650897/142838283-2d5612e5-ec20-4457-981b-ee9cf0e551ac.png)

Then , I need to remove the vector and the screen label .  But failed to remove the screenlabel .

![image](https://user-images.githubusercontent.com/52650897/142838376-8a5a4fe9-927a-442f-b2f9-482b47b5ba7b.png)

Could you please help me to manage these vectors and labels properly ?

**Comment by mousebird** [comment]
Deleting screen labels definitely works, so there's something with your implementation.
Remember you have to save the ComponentObject that comes back from the addScreenLabels call and then hand that over to removeObjects.

**Comment by RookieFeng** [comment]
I am familiar with the use of `componentObject` .  It's not  improper use caused the error.  

After testing, I found the following rules:

A: For a single screenLabel

1. If  layoutImportance (such as 200) is set to the label , then the label cannot be removed from the screen. Unless set to MAXFLOAT or zero.
2. The layoutImportance affects the position of the screenlabel. Some offset will occur.

B: For a screenLabel with the ‘layoutVec’ attribute .

1. If you do not set layoutImportance  or  set layoutImportance to MAXFLOAT, the label will be displayed at (0, 0).
2. Based on the conclusion of B-1, in order to enable the label to be displayed next to the line. The layoutImportance must be set (such as 200). However, at this time, the condition of A-1 is satisfied, and screenLabel cannot be removed.

This is frustrating

**Comment by mousebird** [comment]
Setting a layoutImportance to 200 will route the label through the layout engine.  Setting it to MAXFLOAT will add it directly without a delay.

We use the former heavily in vector tiles, so I suspect there's something to do with how you're doing this.
Can you reproduce this with changes to the ScreenLabel test case in the AutoTester app for example?

**Comment by RookieFeng** [comment]
I sent a test case to  email  contact@mousebirdconsulting.com

**Comment by mousebird** [comment]
Nice test case!
It looks like this was a problem in the main branch.
For the moment, just switch to develop.  We'll either hotfix main or accelerate the release of the next version next week.

**Comment by RookieFeng** [comment]
Thanks a lot ! I am looking forward to see the new version .
