### ISSUE TITLE
crashes on version 3.4 

### ISSUE THREAD

**Issue by RookieFeng** [mousebird-consulting-inc/WhirlyGlobe#1470]
There have been many crashes here ： 

![image](https://user-images.githubusercontent.com/52650897/143186651-90f8c430-74bc-47f7-b248-9b2918cc3cda.png)

Backtrace : 
![image](https://user-images.githubusercontent.com/52650897/143187275-1fd300bb-123f-4151-9520-63289fe8ee7a.png)

**Comment by mousebird** [comment]
You need to turn off the Metal api checking layer.  It’s in the settings
and it’s fairly buggy.

**Comment by mousebird** [comment]
That's on the Diagnostics tab.  You also want to turn off GPU Frame Capture on the Options tab.
If you're running on the simulator, Metal is always a bit weird.

**Comment by RookieFeng** [comment]
Thanks !  It's running  on real devices . Metal  API Validation had been closed .  GPU Frame Capture  is now disabled, and I will continue to do some tests.
