### ISSUE TITLE
MaplyMovingScreenLabel doesn't change location and AutoTester is missing working test case 

### ISSUE THREAD

**Issue by paulgee31** [mousebird-consulting-inc/WhirlyGlobe#1478]
MaplyMovingScreenLabel displays at start location but never animates to endLoc.

Checking the AutoTester MovingScreenLabelsTestCase.swift file it contains only stubs but no test scenario. 

Below is my test snippet:

       let label = MaplyMovingScreenLabel()
        label.loc = MaplyCoordinateMakeWithDegrees(0.167914, 51.197795)
        label.endLoc = MaplyCoordinateMakeWithDegrees(-0.119376, 51.225319)
        label.duration = TimeInterval(10)
        label.layoutImportance = MAXFLOAT
        label.text = "Test Text"
        
        let font = UIFont.systemFont(ofSize: 14.0)
        
        theViewC?.addScreenLabels([label], desc: [kMaplyFont: font,
        kMaplyTextColor: UIColor.red,
        kMaplyEnable: true ])

**Comment by mousebird** [comment]
Good catch.  I updated the test case and fixed the bug.
Let me know if those work for you on the develop branch.

**Comment by TimSylvester-mousebird** [comment]
Works for me.
