### ISSUE TITLE
kMaplyVecWidth has no effect when used with addVectors

### ISSUE THREAD

**Issue by paulgee31** [mousebird-consulting-inc/WhirlyGlobe#1479]
When setting kMaplyVecWidth as part of the dictionary passed to addVectors, it has no effect on the thickness of the line used to draw the MaplyVectorObjects.

This can be seen in the AutoTester's Vectors test case, where kMaplyVecWidth is set to 4.0 but is drawing a 1.0 thickness line. The value can be significantly increased with no effect.

This was observed on the develop branch.

**Comment by mousebird** [comment]
Ah, that's right.  Metal did away with line width and so now we have to rely on the Wide Vectors to do this.
You can get sort of the same if you turn on the performance mode for wide vectors.

**Comment by paulgee31** [comment]
I'll try wide vectors, thanks for fixing the MovingScreenLabels.

**Comment by TimSylvester-mousebird** [comment]
@paulgee31 Not quite, the necessary value is:

```
//kMaplyShader:kMaplyShaderWideVectorPerformance
kMaplyWideVecImpl:kMaplyWideVecImplPerf,
```

The former changes the shader directly, but that shader takes different inputs.  The latter changes the shader indirectly and also makes the necessary changes to the associated attributes.
