### ISSUE TITLE
addWideVectors ignores attributes of vector objects 

### ISSUE THREAD

**Issue by paulgee31** [mousebird-consulting-inc/WhirlyGlobe#1480]
Setting the colour as part of the attributes dictionary for a specific Vector Object works when addVectors is used however the colour defaults to white when addWideVectors is called.

Rightly or wrongly I would have expected the behaviour to be the same.

Code snippet which demonstrates issue using develop branch.

let points  = [MaplyCoordinateMakeWithDegrees(0.167914, 51.197795),MaplyCoordinateMakeWithDegrees(-0.119376, 51.225319)]

let vector = MaplyVectorObject(lineString: points, numCoords: 2, attributes: [kMaplyColor:UIColor.orange])
    
theViewC?.addWideVectors([vector], desc: [kMaplyDrawPriority: kMaplyVectorDrawPriorityDefault+200,kMaplyVecWidth:6], mode: MaplyThreadMode.current)

**Comment by mousebird** [comment]
That does make sense.
Is this something that used to work in 2?

**Comment by paulgee31** [comment]
Never tried it in v2 as addVectors supported different width settings and also respected the colour attributes for individual vectors. 

With the switch to v3 and metal not supporting vector widths in addVectors, we will need to switch to addWideVectors to get the width but also require the colour settings support for individual vectors, so we can build multi coloured line segments.

It also might be useful for others to know that for transparency and colour is handled different in v3 to v2.

In v2 transparent colours where defined like this (eg. white with an alpha of 0.2):
		color=[UIColor colorWithRed:0.2 green:0.2 blue:0.2 alpha:0.2];
In v3 the alpha works as you would typically expect
		color=[UIColor colorWithRed:1.0 green:1.0 blue:1.0 alpha:0.2];

**Comment by TimSylvester-mousebird** [comment]
Unfortunately, this is not a simple change I can sneak in.  `addVectors` checks for colors in the vector object attributes and signals the drawable builder and this flows through the drawable builder into the attributes, and I wouldn't be surprised if shader changes are needed in one or both wide vector implementations.

The blending behavior you describe is related to "pre-multiplied alpha".  This also differs between the Metal and OpenGL implementations due to differences in the way those APIs work.  There's now some support for specifying this at a low level, see `setBlendPremultipliedAlpha`, but it's not exposed in the API.

I'd agree that it should be mentioned somewhere.  I can't remember if there's a "migration guide" or list of breaking changes anywhere...

**Comment by paulgee31** [comment]
Thanks for the update. Can you confirm this will be scheduled into a future sprint? We will put our migration to V3 on hold until this functionality is restored, as it is linked to a key feature of our app.

**Comment by TimSylvester-mousebird** [comment]
If I understand correctly, you can achieve the same results by adding the wide vectors individually.  This will result in more drawables and lower performance, but may still be practical.  If you can group them and add all the items of each color at once, that would help.

Do you know which wide vector implementation you'll be using?  The performance version does almost all the work in the shaders and so is much faster, but doesn't (yet) support all the features of the legacy implementation.  It's also iOS-only at this point.

We don't generally schedule changes or releases except under a support contract.  If you were to figure out whether shader changes are needed for the legacy/performance implementations and perhaps do some of the setup, that would make me more likely to work on it when I have overhead time.

**Comment by paulgee31** [comment]
Yes that would be a work around if we need to go down that route. 

Our application is iOS only and we do have a support contract in place. Our requirement is quite straightforward (to me anyway😉),  in essence we are just trying to achieve the same behaviour that was present in addVectors V2 (width  and  color attributes) we'd be looking for the performance shader to support this.

**Comment by TimSylvester-mousebird** [comment]
Ah, ok, I will leave it to Steve to make any commitments, though.

**Comment by mousebird** [comment]
Yah, Paul's on support and I'd like to get this sorted for them.
Let me review and Tim and I will talk.

**Comment by TimSylvester-mousebird** [comment]
@paulgee31 Can you try out the latest develop and see if it works for you?

**Comment by paulgee31** [comment]
@TimSylvester-mousebird  I'm please to report it works for the default shader. Many thanks for the quick fix.

The performance shader has the following error but I don't know if that is expected....

BasicDrawableMTL: Failed to set up render state because:
Error Domain=AGXMetalA9 Code=3 "Cannot convert attribute from MTLAttributeFormatFloat4 to int1 or uint1" UserInfo={NSLocalizedDescription=Cannot convert attribute from MTLAttributeFormatFloat4 to int1 or uint1}

**Comment by TimSylvester-mousebird** [comment]
I think we ran into that before, are you specifying the shader directly rather than using the `kMaplyWideVecImpl` option?

The "Wide Vectors" AutoTester case now includes the default and performance implementations, so you can use that as an example.

**Comment by paulgee31** [comment]
Yep I was specifying the shader directly, following the "Wide Vectors" example works perfectly. Many thanks.
