### ISSUE TITLE
Tilt corrupts display after using setTiltMinHeight 

### ISSUE THREAD

**Issue by paulgee31** [mousebird-consulting-inc/WhirlyGlobe#1481]
Having set a tilt threshold in v3 using parameters as below:
      `  theViewC?.setTiltMinHeight(0.001, maxHeight: 0.08, minTilt: 1.51771169, maxTilt: 0.0)`

The display corrupts as per image below:

![IMG_1179](https://user-images.githubusercontent.com/1561610/148230862-cc37fb0e-77fe-4ca6-80ac-feecbbe06453.PNG)

**Comment by mousebird** [comment]
Looks like we need a tilt test in the AutoTester.

**Comment by paulgee31** [comment]
The LIDAR test uses tilt but is currently broken 😬

**Comment by TimSylvester-mousebird** [comment]
I added it to the billboard case.  Seems to be happening in the shaders, but I can't tell what's going on by looking at it.

https://user-images.githubusercontent.com/71895881/150174924-ed50c432-9e7a-4edb-8c32-9ef20ee0895d.mp4

**Comment by mousebird** [comment]
Was a shader bug.  Fixed now.
Just pull the latest develop.
