### ISSUE TITLE
Tweak minimum overlap in layout manager

### ISSUE THREAD

**Issue by ivan-avalos** [mousebird-consulting-inc/WhirlyGlobe#1484]
Hello! I'm really loving WhirlyGlobe! I'd like to know how to reduce the level of zoom required to show markers that are close together in the map. I'm doing marker clustering and I really need this. I was trying to set `layoutImportance` (right now = 1.0) to different values, and I can't see any noticeable difference. How can I interact with the layout manager to change its behavior?

**Comment by mousebird** [comment]
layoutImportance just controls which markers are more important.
You could try making the layout size bigger.  There should be a layoutSize on those objects.
