### ISSUE TITLE
How to find screen markers at a point?

### ISSUE THREAD

**Issue by akovalov** [mousebird-consulting-inc/WhirlyGlobe#1489]
There is [findObjectAtLocation:](https://mousebird-consulting-inc.github.io/WhirlyGlobe/reference/ios_3_0/Classes/WhirlyGlobeViewController.html#/c:objc(cs)WhirlyGlobeViewController(im)findObjectAtLocation:) function in `WhirlyGlobeViewController` that returns selectable object (screen marker in my case). 
However, there is no similar function for `MaplyViewController`. 

The [objectsAtCoord:](https://mousebird-consulting-inc.github.io/WhirlyGlobe/reference/ios_3_0/Classes/MaplyBaseViewController.html#/c:objc(cs)MaplyBaseViewController(im)objectsAtCoord:) in `MaplyBaseViewController` does not seem to work at all. 

In my case, I've added a long press gesture and would like to find screen markers (markers are added and visible on the map) at the gesture point.

**Comment by mousebird** [comment]
@TimSylvester-mousebird I know you're using this in the 2D map.

**Comment by TimSylvester-mousebird** [comment]
`objectsAtCoord` just calls `findVectorsInPoint` which searches vector objects, not markers.

The `userDidTap` delegates are using `selectMultipleLabelsAndMarkersForScreenPoint`.  Unfortunately, it doesn't look like that's accessible outside the interaction layer.

It would probably be good to expose that latter to direct calls, and perhaps an equivalent to `userDidTapLayerThread:(WhirlyGlobeTapMessage*)` which searches both.

I'll try to include that in the next sprint, but it should be fairly simple if you want to take a stab at it.

**Comment by akovalov** [comment]
@TimSylvester-mousebird can you please take a look at PR https://github.com/mousebird-consulting-inc/WhirlyGlobe/pull/1491? Thank you.
