### ISSUE TITLE
[MTLDebugRenderCommandEncoder validateCommonDrawErrors:]

### ISSUE THREAD

**Issue by anya-sverdlova** [mousebird-consulting-inc/WhirlyGlobe#1490]
Had a crash trying to run controller with map: 
-[MTLDebugRenderCommandEncoder validateCommonDrawErrors:]:5252: failed assertion `Draw Errors Validation
Fragment Function(fragmentTri_multiTex): the offset into the buffer fragArgs that is bound at buffer index 2 must be a multiple of 256 but was set to 160.
The strange stuff is I didn't do any additional setup, only copied your code from tutorial to real project. 
Any idea why is it happen? 
<img width="1010" alt="Screenshot 2022-01-25 at 18 56 25" src="https://user-images.githubusercontent.com/6271222/151023364-3bb53dd7-4864-4431-8dbb-430d15b0c03d.png">

Also I had more than 20000 warnings after installing pod. Is it how it suppose to be?

**Comment by mousebird** [comment]
First question is hardware or simulator.  The simulator is a bit undependable.
Then, you might try turning off the Metal verification and debugging options in the project.  Those can be a bit flakey.

**Comment by ivan-avalos** [comment]
I'm getting the same error. How do I turn off those things? I really need to take some screenshots for the App Store, and the app keeps crashing in the simulator.

**Comment by sjg-wdw** [comment]
Under Edit Scheme look in the Options and Diagnostics.
Select Disable for GPU Frame Capture and turn off everything under Metal.
