### ISSUE TITLE
Mapbox style "interpolate" and "match" crash

### ISSUE THREAD

**Issue by akovalov** [mousebird-consulting-inc/WhirlyGlobe#1498]
When use a Mapbox style json file with the examples below of `interpolate` and `match` for width or color it crashes. Not sure that because of this exactly but looks like they are not supported inside the SDK. 

```
"line-width": [
                    "interpolate",
                    ["linear"],
                    ["zoom"],
                    3,
                    0.5,
                    10,
                    2
                ],

"line-color": [
                    "interpolate",
                    ["linear"],
                    ["zoom"],
                    3,
                    "hsl(230, 15%, 77%)",
                    7,
                    "hsl(230, 8%, 62%)"
                ]

"fill-color": [
                    "match",
                    ["get", "class"],
                    "snow",
                    "hsl(35, 14%, 100%)",
                    "hsl(81, 38%, 81%)"
                ],
```

Crash happens in `MapboxVectorStyleSetC.cpp` in the following function because `stops` is `NULL`. 
<img width="1392" alt="Screenshot 2022-01-29 at 11 55 28" src="https://user-images.githubusercontent.com/9693643/151656497-ed0f7142-d144-4a0a-a22e-5b0b9ab8f878.png">

Please see test Mapbox style json that crashes. 
[interpolate_match_style.json.zip](https://github.com/mousebird-consulting-inc/WhirlyGlobe/files/7963419/interpolate_match_style.json.zip)

Is it something that can be fixed or added support of relatively easily or it's a lot of work to do?

**Comment by akovalov** [comment]
Tried to replace "interpolate" function in json file with "stops" and no more crash (so crash was on parsing "interpolate" for color or width). However, the style does not look like it should be at all (screenshot). Attached a json style without interpolate just in case it will be helpful. 
Just wondering if you have any idea here to get this mapbox style working? Thank you.

![IMG_C57789A72E70-1](https://user-images.githubusercontent.com/9693643/151675463-64e7cb87-b706-4384-ab0a-c2eea86203e2.jpeg)

[light_map_style.json.zip](https://github.com/mousebird-consulting-inc/WhirlyGlobe/files/7964470/light_map_style.json.zip)

**Comment by mousebird** [comment]
Mapbox style sheets are complex and I'm afraid we really only dig into these problems for customers.
The AutoTester uses a few MapTiler styles that work fairly well.  I'd compare what features those are using to your style sheet.
