### ISSUE TITLE
MaplyVectorObject Curve smoothing problem

### ISSUE THREAD

**Issue by ForTraces** [mousebird-consulting-inc/WhirlyGlobe#1508]
Hello:
  Version：2.6.2 , Use the following method  
   MaplyVectorObject *vec = [[MaplyVectorObject alloc] initWithGeoJSONDictionary:responseObj];
        [self.baseViewC addWideVectors:@[vec] desc: @{
            kMaplyColor:[UIColor yellowColor], //STColor(50, 201, 99)
            kMaplyDrawPriority: @(kMaplyVectorDrawPriorityDefault + 110),
            kMaplyVecWidth: @(2)
        } mode:MaplyThreadCurrent];
<img width="603" alt="图片" src="https://user-images.githubusercontent.com/8295724/154190635-aa99ea4f-3a1b-4ef0-8aa9-1bb1c9157d83.png">

The web side uses mapbox to load the same data and the effect is as follows
<img width="577" alt="图片" src="https://user-images.githubusercontent.com/8295724/154190466-3c6b988b-3eb0-4d1b-a1a2-a2218ef5c393.png">

What do I need to do if I want the curve to be smooth?

**Comment by mousebird** [comment]
Float vs double most likely.
There are ways to work around that, such as defining a center and building the geometry around that center.
Are you on support?

**Comment by ForTraces** [comment]
> Float vs double most likely. There are ways to work around that, such as defining a center and building the geometry around that center. Are you on support?

<img width="326" alt="图片" src="https://user-images.githubusercontent.com/8295724/154415532-e4e00a25-6e89-4c97-9aa9-5ae736455b2c.png">


The red dot in the picture is the latitude and longitude point. How can the drawn curve be smooth?

**Comment by mousebird** [comment]
You need to define a center and then offset all the points from that center.
