### ISSUE TITLE
Execution of the command buffer was aborted due to an error during execution. Caused GPU Address Fault Error 

### ISSUE THREAD

**Issue by akovalov** [mousebird-consulting-inc/WhirlyGlobe#1510]
After some time running in the background when went to foreground the WhirlyGlobe constantly logs the following error and map became unresponsive and constantly glitches. 
```
Execution of the command buffer was aborted due to an error during execution. 
Caused GPU Address Fault Error (0000000b:kIOGPUCommandBufferCallbackErrorPageFault)
```
Any ideas?

**Comment by akovalov** [comment]
Couldn't yet reproduce in AutoTester. 
Metal API Validation in scheme Diagnostics is disabled (if I understood you correctly). 
Looks like the error is caused if `animate(toPosition` method has been called (once or multiple times) in background.

**Comment by mousebird** [comment]
Are you calling it while backgrounded?

**Comment by akovalov** [comment]
@mousebird yes

**Comment by mousebird** [comment]
In general it's bad to call things while backgrounded.

**Comment by akovalov** [comment]
@mousebird yes, I assumed that this is the case. Understood, will change to not call this in background. Thanks.

**Comment by zzjiong** [comment]
> @mousebird yes, I assumed that this is the case. Understood, will change to not call this in background. Thanks.

Have you solved your problem? I have encountered the same problem. and we not call animate toPosition method in background

**Comment by akovalov** [comment]
@zzjiong as I understood from the mousebird's reply above any updates to the map while the app is running in the background are bad. In my case, I've made sure to not make any updates on the map until the app is in the foreground.
