### ISSUE TITLE
The "background" layer in Mapbox like style is not supported

### ISSUE THREAD

**Issue by akovalov** [mousebird-consulting-inc/WhirlyGlobe#1513]
Looks like the background layer from the style is not supported. This is used to color the background layer when use a vector mbtiles file. Is it possible to add it? Or guide me please where to look at to make a PR.
```
"layers": [
    {
      "id": "background",
      "type": "background",
      "paint": {"background-color": "hsl(47, 26%, 88%)"}
    },
```

**Comment by mousebird** [comment]
Can you take a look at this one @TimSylvester-mousebird?

**Comment by TimSylvester-mousebird** [comment]
The background layer is handled by `MapboxVectorLayerBackground`. As with other layers, only a subset of the options are supported, but background color is one of them.

Does it work if you use an RGB color?  Your example reminds me of something I noticed a while ago, that there are two color parsing methods, one in the basic dictionary code and one in the stylesheet code, and the dictionary version is much simpler and does not support some features, particularly HSL.  Possibly that layer is just using that version.

**Comment by akovalov** [comment]
@TimSylvester-mousebird the issue is in the `MapboxVectorTileParser.cpp`, where background layer parsing code is commented out, please see the screenshot.

<img width="983" alt="Screenshot 2022-03-07 at 13 02 05" src="https://user-images.githubusercontent.com/9693643/157019251-3b7ad259-f4d4-4f2b-8cf7-214649f59d94.png">

I've update it to the following

```
// Call background
    if (const auto backgroundStyle = styleDelegate->backgroundStyle(styleInst)) {
        auto styleData = std::make_shared<VectorTileData>(*tileData);
        std::vector<VectorObjectRef> objs;
        backgroundStyle->buildObjects(styleInst, objs, styleData, nullptr, cancelFn);

        tileData->mergeFrom(styleData.get());
    }
```

and it looks OK in 2d map 
<img width="300" src="https://user-images.githubusercontent.com/9693643/157025770-0bac805d-cc4d-4316-a1f4-35a7d6dd8288.jpeg">

but in globe looks like this - flat layer inside globe
<img width="300" src="https://user-images.githubusercontent.com/9693643/157027083-7ba7f59b-6da0-4983-bc40-cd29e0b01e7a.jpeg">
<img width="300" src="https://user-images.githubusercontent.com/9693643/157027219-e1c10768-6e47-4119-b227-593a9c2596b5.jpeg">

Can you check it please or point me to how to fix it so I can submit a PR?

**Comment by mousebird** [comment]
There's a couple things going on here.
First, we tend to pull the color out of the background layer and use it as our clear color for the 2D map.
For the 3D globe we actually render most of the geometry into an image so it can be plastered on to the globe and follow the curvature.
You'll see examples of that in the AutoTester app.  Select the globe option.
