### ISSUE TITLE
[Android] Cannot Delete Markers and Labels from Globe (binary v3.3)

### ISSUE THREAD

**Issue by kevinthakar** [mousebird-consulting-inc/WhirlyGlobe#1515]
I'm performing label and marker addition/deletion using a handler every x seconds.
Labels and markers addition/deletion was working fine in the previous binaries, but since I've updated to 3.3, deletion doesn't seem to work. In some cases, a label is deleted but its corresponding marker at the same position still remains on the globe. Most of the times nothing gets deleted.
Any clue as to why this might be happening?
This is what I'm currently doing -
1. Initialize labelArrayList and markerArrayList.
2. Add ScreenLabel and ScreenMarker objects to the above 2 lists.
3. Call addScreenMarkers and addScreenLabels, passing to it the above 2 lists. Store the result in 2 separate ComponentObject objects (co1 and co2).
4. Add co1 and co2 to componentObjectArrayList.
5. Remove co1 and co2 in the next iteration using removeObject function.

Happy to provide more info, logs.

**Comment by mousebird** [comment]
Can you take a look at this one @TimSylvester-mousebird 
Thanks.

**Comment by TimSylvester-mousebird** [comment]
That pattern is used in several AutoTester cases.

Can you provide sample code, or a patch to one of those AutoTester cases which demonstrates the problem?

**Comment by kevinthakar** [comment]
I referred to MarkersTestCase.java and ScreenLabelsTestCase.java while writing for my own use case. I added v3.3 to my project about a month ago, and I'm facing the deletion problem since then. The following code worked fine before that, though.

`    private ArrayList<ScreenMarker> markerImageArrayList = new ArrayList<>(); //list of all my markers
    private List<ScreenLabel> labelTextArrayList = new ArrayList<>(); //list of all my labels
    private ComponentObject markersObject, labelsObject;
    private ArrayList<ComponentObject> componentObjects = new ArrayList<>();
    
    .
    .
    .

    public void InsertLabelsAndMarkers(ArrayList<Object> myList) {

        MarkerInfo markerInfo = new MarkerInfo();
        LabelInfo labelInfo = new LabelInfo();
        Point2d markerSize = new Point2d(28, 56);
        Bitmap markerBitmap = BitmapFactory.decodeResource(getContext().getResources(), R.drawable.ic_marker);
        //componentObjects.clear();

        if (labelsObject != null) { //if labels exist on the globe
            globeControl.removeObject(labelsObject, RenderControllerInterface.ThreadMode.ThreadAny);
        }

        if(markersObject != null) {
            globeControl.removeObject(markersObject, RenderControllerInterface.ThreadMode.ThreadAny);
        }


        markerImageArrayList.clear();
        labelTextArrayList.clear();

        labelInfo.setTextColor(Color.rgb(100,239,255));
        labelInfo.setOutlineColor(Color.BLACK);
        labelInfo.setOutlineSize(2f);

        Typeface typeface = Typeface.createFromAsset(getContext().getAssets(), "Fonts/poppinsextrabold.ttf");
        labelInfo.setTypeface(typeface);
        labelInfo.setFontSize(36f);
        labelInfo.setTextJustify(LabelInfo.TextJustify.TextCenter); // aligns text of the label

        for (Object X : myList) {

            ScreenMarker screenMarker = new ScreenMarker();
            screenMarker.loc = Point2d.FromDegrees(X.getLongitude(), X.getLatitude()); // Longitude, Latitude
            screenMarker.image = markerBitmap;
            screenMarker.size = markerSize;
            screenMarker.selectable = false;

            ScreenLabel label = new ScreenLabel();
            label.userObject = X;
            label.text = wrapper(X.getText());
            label.selectable = true;
            
            labelTextArrayList.add(label);
            markerImageArrayList.add(screenMarker);
        }

        markersObject = globeControl.addScreenMarkers(markerImageArrayList, markerInfo, BaseController.ThreadMode.ThreadAny);
        labelsObject = globeControl.addScreenLabels(labelTextArrayList, labelInfo, BaseController.ThreadMode.ThreadAny);

        if(labelsObject != null) {
            componentObjects.add(labelsObject);
        }

        if (markersObject != null) {
            componentObjects.add(markersObject);
        }
    }
`

**Comment by kevinthakar** [comment]
I referred to MarkersTestCase.java and ScreenLabelsTestCase.java while writing for my own use case. I added v3.3 to my project about a month ago, and I'm facing the deletion problem since then. The following code worked fine before that, though.

`    private ArrayList<ScreenMarker> markerImageArrayList = new ArrayList<>(); //list of all my markers
    private List<ScreenLabel> labelTextArrayList = new ArrayList<>(); //list of all my labels
    private ComponentObject markersObject, labelsObject;
    private ArrayList<ComponentObject> componentObjects = new ArrayList<>();
    
    .
    .
    .

    public void InsertLabelsAndMarkers(ArrayList<Object> myList) {

        MarkerInfo markerInfo = new MarkerInfo();
        LabelInfo labelInfo = new LabelInfo();
        Point2d markerSize = new Point2d(28, 56);
        Bitmap markerBitmap = BitmapFactory.decodeResource(getContext().getResources(), R.drawable.ic_marker);
        //componentObjects.clear();

        if (labelsObject != null) { //if labels exist on the globe
            globeControl.removeObject(labelsObject, RenderControllerInterface.ThreadMode.ThreadAny);
        }

        if(markersObject != null) {
            globeControl.removeObject(markersObject, RenderControllerInterface.ThreadMode.ThreadAny);
        }


        markerImageArrayList.clear();
        labelTextArrayList.clear();

        labelInfo.setTextColor(Color.rgb(100,239,255));
        labelInfo.setOutlineColor(Color.BLACK);
        labelInfo.setOutlineSize(2f);

        Typeface typeface = Typeface.createFromAsset(getContext().getAssets(), "Fonts/poppinsextrabold.ttf");
        labelInfo.setTypeface(typeface);
        labelInfo.setFontSize(36f);
        labelInfo.setTextJustify(LabelInfo.TextJustify.TextCenter); // aligns text of the label

        for (Object X : myList) {

            ScreenMarker screenMarker = new ScreenMarker();
            screenMarker.loc = Point2d.FromDegrees(X.getLongitude(), X.getLatitude()); // Longitude, Latitude
            screenMarker.image = markerBitmap;
            screenMarker.size = markerSize;
            screenMarker.selectable = false;

            ScreenLabel label = new ScreenLabel();
            label.userObject = X;
            label.text = wrapper(X.getText());
            label.selectable = true;
            
            labelTextArrayList.add(label);
            markerImageArrayList.add(screenMarker);
        }

        markersObject = globeControl.addScreenMarkers(markerImageArrayList, markerInfo, BaseController.ThreadMode.ThreadAny);
        labelsObject = globeControl.addScreenLabels(labelTextArrayList, labelInfo, BaseController.ThreadMode.ThreadAny);

        if(labelsObject != null) {
            componentObjects.add(labelsObject);
        }

        if (markersObject != null) {
            componentObjects.add(markersObject);
        }
    }`

**Comment by kevinthakar** [comment]
I referred to MarkersTestCase.java and ScreenLabelsTestCase.java while writing for my own use case. I added v3.3 to my project about a month ago, and I'm facing the deletion problem since then. The following code worked fine before that, though.

`public void InsertLabelsAndMarkers(ArrayList<Object> myList) {

    ArrayList markerImageArrayList = new ArrayList<>(); //list of all my markers
    ArrayList labelTextArrayList = new ArrayList<>(); //list of all my labels
    ComponentObject markersObject, labelsObject;
    ArrayList componentObjects = new ArrayList<>();

    MarkerInfo markerInfo = new MarkerInfo();
    LabelInfo labelInfo = new LabelInfo();
    Point2d markerSize = new Point2d(28, 56);
    Bitmap markerBitmap = BitmapFactory.decodeResource(getContext().getResources(), R.drawable.ic_marker);
    //componentObjects.clear();

    if (labelsObject != null) { //if labels exist on the globe
        globeControl.removeObject(labelsObject, RenderControllerInterface.ThreadMode.ThreadAny);
    }

    if(markersObject != null) {
        globeControl.removeObject(markersObject, RenderControllerInterface.ThreadMode.ThreadAny);
    }


    markerImageArrayList.clear();
    labelTextArrayList.clear();

    labelInfo.setTextColor(Color.rgb(100,239,255));
    labelInfo.setOutlineColor(Color.BLACK);
    labelInfo.setOutlineSize(2f);

    Typeface typeface = Typeface.createFromAsset(getContext().getAssets(), "Fonts/poppinsextrabold.ttf");
    labelInfo.setTypeface(typeface);
    labelInfo.setFontSize(36f);
    labelInfo.setTextJustify(LabelInfo.TextJustify.TextCenter); // aligns text of the label

    for (Object X : myList) {

        ScreenMarker screenMarker = new ScreenMarker();
        screenMarker.loc = Point2d.FromDegrees(X.getLongitude(), X.getLatitude()); // Longitude, Latitude
        screenMarker.image = markerBitmap;
        screenMarker.size = markerSize;
        screenMarker.selectable = false;

        ScreenLabel label = new ScreenLabel();
        label.userObject = X;
        label.text = wrapper(X.getText());
        label.selectable = true;
        
        labelTextArrayList.add(label);
        markerImageArrayList.add(screenMarker);
    }

    markersObject = globeControl.addScreenMarkers(markerImageArrayList, markerInfo, BaseController.ThreadMode.ThreadAny);
    labelsObject = globeControl.addScreenLabels(labelTextArrayList, labelInfo, BaseController.ThreadMode.ThreadAny);

    if(labelsObject != null) {
        componentObjects.add(labelsObject);
    }

    if (markersObject != null) {
        componentObjects.add(markersObject);
    }
}`

**Comment by TimSylvester-mousebird** [comment]
Well, that leaves some details to the imagination.  Even going back to 3.3 and running something like that on a timer, I don't see any objects being left around.

Is it possible that this method is being run on multiple threads, leading to the value of, e.g., `markerObject` being overwritten?

https://user-images.githubusercontent.com/71895881/158661987-a9f4a744-4138-48c9-8a25-a262d371f1ac.mp4

By the way, for best performance, create the new objects first with `enabled=false` and `ThreadCurrent` (ideally while operating on a non-UI thread), then remove the old objects and enable the new ones.  This makes it unlikely that a frame is rendered between the remove and the add, which leads to flickering.

**Comment by kevinthakar** [comment]
Thanks for clarifying, @TimSylvester-mousebird .
Deletion is working fine, and the video you posted helps conclude the same. I wasn't handling the data list properly before calling InsertLabelsAndMarkers function.

"By the way, for best performance, create the new objects first with enabled=false and ThreadCurrent (ideally while operating on a non-UI thread), then remove the old objects and enable the new ones. This makes it unlikely that a frame is rendered between the remove and the add, which leads to flickering."
Thanks for the tip! :)
