### ISSUE TITLE
Magenta color appear from time to time

### ISSUE THREAD

**Issue by akovalov** [mousebird-consulting-inc/WhirlyGlobe#1519]
Such distortions appear from time to time and then disappear.
No exact steps or circumstances have been found yet.

<img width="328" alt="Screenshot 2022-03-16 at 10 44 21" src="https://user-images.githubusercontent.com/9693643/158552726-a5449d39-f6ae-4584-8978-433f07fe093e.png">

OpenStreetMap mbtiles file is used along with Mapbox-like stylesheet.
Image-vector hybrid code like in AutoTester is used now, however looks like such distortions appeared also earlier when just vector interpreter was used. 

Do you have any suggestions please?

**Comment by mousebird** [comment]
See if you've got an Metal error printing out when it happens.
