### ISSUE TITLE
Occasional text rendering artifacts with MaplyScreenLabel

### ISSUE THREAD

**Issue by JesseCrocker** [mousebird-consulting-inc/WhirlyGlobe#165]
![photo](https://cloud.githubusercontent.com/assets/2048291/2755211/e6e58798-c964-11e3-97dc-73eac64f6871.PNG)

**Comment by mousebird** [comment]
I actually know what this is now.  It's caused by neighboring glyphs in the texture atlas.  It shouldn't appear again, but if it does we can just add a bigger buffer around the glyphs.

**Comment by TimSylvester-mousebird** [comment]
This is still happening in 3.4 even with large buffer sizes.  Enabling clearing of texture atlases only makes things worse.

<img src="https://user-images.githubusercontent.com/71895881/137554977-9a456f13-424c-48ad-88ab-966a14469429.jpg"/>
