### ISSUE TITLE
Linear Feature Selection - General Case

### ISSUE THREAD

**Issue by mousebird** [mousebird-consulting-inc/WhirlyGlobe#166]
Need to implement the general case of linear feature selection.  This means projecting the points to the screen and doing distance testing.

**Comment by mousebird** [comment]
We'll revisit this based on user requirements.

**Comment by sveta-wl** [comment]
Hi @mousebird ! 
Is this feature already implemented? Does it work for Android?
If not, what is the workaround to select a linear created from GeoJson? 
Thanks for help

**Comment by mousebird** [comment]
I think it's there in 3.0, but I don't believe it is in 2.6 for Android.

**Comment by sveta-wl** [comment]
Thank you for your reply.
The latest [release](https://github.com/mousebird/WhirlyGlobe/releases) is 2.6.2 from Jul19. When will be 3.0 released?

**Comment by mousebird** [comment]
Are you on support?  It's something I'd check for in 3.0 if you were.

**Comment by sveta-wl** [comment]
No, I'm not...
Do you accept pull requests?

**Comment by mousebird** [comment]
Sure.
