### ISSUE TITLE
Is there a way to scale down MaplyScreenMarkers a little as you zoom out?

### ISSUE THREAD

**Issue by amirfl** [mousebird-consulting-inc/WhirlyGlobe#416]
I know MaplyMarker Keeps the same geographic size on the map as you zoom in and out. MaplyScreenMarker keeps the same screen size as you zoom in and out.

The problem with the screen markers is that as you zoom out, the markers get too big in relation to the globe. With a MaplyMarker there is the opposite problem - the markers get way too small when you zoom out and too big when you are zoomed in closely to the marker's location.

Is there a way to get the best of both worlds? In other words, to cause a screen marker to scale down just a specified amount as you zoom out?

**Comment by mousebird** [comment]
I've contemplated implementing that one.  It's be great to have min/max size and a range to scale between.

I don't think it would be all that hard.  The screen markers (and labels) are run by shaders now and I've got a pretty good grip on modifying them.  The harder part would be updating the layout and selection logic, though that's all centralized now.

I'll put it on the feature request pile.  If someone wants to pay for it, I could do it immediately.

**Comment by amirfl** [comment]
I found a temporary solution. Not the most efficient though.  
I've created an extra level of markers, showing the same landmarks as the other level, but with smaller icons. Then, I just set different visibility values for each level of data.

**Comment by mousebird** [comment]
An excellent workaround, if not nearly as much fun.

I'm going to keep this on the pile for feature requests.

**Comment by amirfl** [comment]
:+1:

**Comment by Spotunes** [comment]
> I've contemplated implementing that one. It's be great to have min/max size and a range to scale between.
> 
> I don't think it would be all that hard. The screen markers (and labels) are run by shaders now and I've got a pretty good grip on modifying them. The harder part would be updating the layout and selection logic, though that's all centralized now.
> 
> I'll put it on the feature request pile. If someone wants to pay for it, I could do it immediately.

Hi I would pay for this feature including support for 3d objects markers.  Please reachout to discuss.

**Comment by mousebird** [comment]
Neat!  Send me your email at contact@mousebirdconsulting.com and we'll talk!
