### ISSUE TITLE
MaplyViewController didMove method

### ISSUE THREAD

**Issue by jerald-acacus** [mousebird-consulting-inc/WhirlyGlobe#435]
Is there a reason why there is no didMove method for MaplyViewController when it is implemented in WhirlyGlobeViewController? Or may be there is another delegate method for it? I am trying to get the current heading of the MaplyViewController while the user moves, zoom, pinch or rotate the map.

**Comment by mousebird** [comment]
Yes, that method really should be there.  I'd also like to move the animation state logic over there at some point.

I'll add this as a feature request.

**Comment by JesseCrocker** [comment]
There are delegate methods for motion starting and stoping `- (void)maplyViewControllerDidStartMoving:userMotion:`  and `- (void)maplyViewController:didStopMoving:userMotion:`

You could easily start a repeating timer in DidStartMoving, and stop it in DidStopMoving, and have the timer query the map location and heading and do what you need to do with it.

**Comment by jerald-acacus** [comment]
@mousebird: I see. I've been looking at how it was implemented in WhirlyGlobeViewController and I'm not sure yet if the same logic would apply with the MaplyViewController. Thanks.

@JesseCrocker: Thanks. That could be a good workaround/hack until the proper method is implemented. Gave me the idea that I can call a method repeatedly and stop it at didStopMoving. I'll try your suggestion to use a timer too and see if it consumes too much device resource then I might have to try implementing the same method as didMove to MaplyViewController.
