### ISSUE TITLE
Add Carthage support

### ISSUE THREAD

**Issue by drhaynes** [mousebird-consulting-inc/WhirlyGlobe#542]
Currently, for two reasons, WhirlyGlobe cannot be used from Carthage.
1. There are no shared schemes in the Xcode project (easily fixed - see below).
2. Carthage does not support static libraries, so a framework target is required.

Point 2 is more involved, naturally.

Steps to reproduce:
- Create an Xcode project, and a `Cartfile` with the following contents:

```
github "mousebird/WhirlyGlobe" == 2.4
```
- Run `carthage update --platform iOS --no-use-binaries --use-submodules`
- When carthage attempts to build, notice the error about lack of shared schemes. Open ./Carthage/Checkouts/WhirlyGlobe/Carthage/WhirlyGlobeSrc/WhirlyGlobe-MaplyComponent/WhirlyGlobe-MaplyComponent.xcodeproj and make the schemes shared, as follows:

<img width="1512" alt="screen shot 2016-03-18 at 13 23 36" src="https://cloud.githubusercontent.com/assets/117291/13879224/3a17dec4-ed0e-11e5-9a08-01ac6a88ac1a.png">
- Run `carthage update --platform iOS --no-use-binaries --use-submodules` again,

Notice carthage outputs the error about no framework target:

```
*** Skipped building WhirlyGlobe due to the error:
Dependency "WhirlyGlobe" has no shared framework schemes for any of the platforms: iOS
```

**Comment by mousebird** [comment]
Interesting.  Hopefully this would be easier to set up than Cocoapods was.

**Comment by mousebird** [comment]
Interestingly, I just ran into a related problem.  I'm going to need to rebuild the main WhirlyGlobe-Maply project, so I'll take a look at this when I do.

**Comment by mousebird** [comment]
In the develop_2_4_1 branch the WhirlyGlobeMaplyComponent project is now set up as a framework build and the schemes are shared.

**Comment by drhaynes** [comment]
Great, will be interesting to see if it works via Carthage now.

**Comment by mousebird** [comment]
Needs a proper test case.  Put this in orbit until we have a customer using Carthage or a user lets us know.

**Comment by jdanthinne** [comment]
Hi,
I've just tried to use Cartage (`carthage update WhirlyGlobe --platform ios --no-use-binaries --use-submodules`), and got the following error:
```
*** Checking out WhirlyGlobe at "v2.4"
A shell task (/usr/bin/env git submodule --quiet update --init --recursive) failed with exit code 1:
error: no such remote ref 79a545a44b863831b1d0d3e3fca6875506a4b4cb
Fetched in submodule path 'third-party/eigen', but it did not contain 79a545a44b863831b1d0d3e3fca6875506a4b4cb. Direct fetching of that commit failed.
```

**Comment by mousebird** [comment]
How about if you use 2.5?

**Comment by jdanthinne** [comment]
Nope
```
*** Checking out WhirlyGlobe at "v2.5"
A shell task (/usr/bin/env git submodule --quiet update --init --recursive) failed with exit code 1:
error: no such remote ref 79a545a44b863831b1d0d3e3fca6875506a4b4cb
Fetched in submodule path 'third-party/eigen', but it did not contain 79a545a44b863831b1d0d3e3fca6875506a4b4cb. Direct fetching of that commit failed.
```

**Comment by mousebird** [comment]
Yup I see it now too.

**Comment by mousebird** [comment]
The problem is the submodule we're using for eigen get reset every so often.  It's a mirror from another system.

You could try updating to the develop branch.  It's stable as we get ready for 2.6.
