### ISSUE TITLE
MaplyVectorObject kMaplyFade has no effect

### ISSUE THREAD

**Issue by bryanheitman** [mousebird-consulting-inc/WhirlyGlobe#788]
kMaplyFade doesn't appear to do anything.

**Comment by mousebird** [comment]
Looks like this is right.  Not going to fix it for 2.5, though.

**Comment by mousebird** [comment]
This is working for me.  What features aren't fading?

**Comment by bryanheitman** [comment]
Vectors and objects added from a (screen markers etc) added from a paging layer.   I think some of them didn’t have a MAXFLOAT but others I believe did.



-Bryan

**Comment by mousebird** [comment]
Oh, I see.  PagingLayer objects are special.  Because we have to use enable/disable with the individual tiles we can't reliably use fade.

**Comment by bryanheitman** [comment]
Ok.. maybe someday

**Comment by mousebird** [comment]
Yeah, someday.  We have the tools down with timed fades, but it'll be a bit of work to make it all match up.

**Comment by bryanheitman** [comment]
Will look cool. FF is doing it with their vector maps.
