### ISSUE TITLE
MaplySticker grouped using multiple drawables

### ISSUE THREAD

**Issue by bryanheitman** [mousebird-consulting-inc/WhirlyGlobe#803]
Opening issue per SteveG.

**Comment by mousebird** [comment]
The problem is if you add 300 of them you get 300 drawables.  It needs to consolidate them like we do everything else.

**Comment by TimSylvester-mousebird** [comment]
Fixed in 3.0.  `addStickers` takes a collection of `MaplySticker` and returns a single `MaplyComponentObject`.
