### ISSUE TITLE
[Android] Wide vectors do not have the same width in portrait and landscape

### ISSUE THREAD

**Issue by jmcazaux** [mousebird-consulting-inc/WhirlyGlobe#890]
This is very strange, but on my Nexus 9 the wide vectors are much wider when the tablet is in portrait mode.

How can that be?

_And before you ask, no I cannot reproduce this in AutoTester as for some reason I cannot compile AutoTester anymore... This is getting on my nerves big time!_ ;)

**Comment by mousebird** [comment]
Do you see this on iOS?  Because it's possible.  The width of vectors is in pixels.

**Comment by jmcazaux** [comment]
I am only toying around on IOS. Nowhere near as advanced yet.

Though it is pixel, they should be square (even though they might not be physically square).

I mean all my other circles are round and my squares are squares.

**Comment by mousebird** [comment]
I did see one difference with iOS so now that's consistent.

This still looks different between platforms.

**Comment by jmcazaux** [comment]
Erm...

Still looks different in landscape & portrait on the same platform...

![wide_vector_width_landscape](https://cloud.githubusercontent.com/assets/2640502/25610839/172ed48a-2f25-11e7-8244-f187a701379f.png)

![wide_vector_width_portrait](https://cloud.githubusercontent.com/assets/2640502/25610856/2226f94e-2f25-11e7-8661-aef0d43c02ce.png)

**Comment by mousebird** [comment]
I realize that.  The code is now identical between platforms, so I'm not clear on why it's only happening on Android.

**Comment by jmcazaux** [comment]
This is still not right.

**Comment by jmcazaux** [comment]
That would be good to solve this one.

not breaking the app, but it gives it a fairly unprofessional look.
